-- CRUD CATEGORIA

SET TERM ^ ;

-- 1) CREATE
CREATE OR ALTER PROCEDURE SP_INSERTAR_CATEGORIA(
  P_NOMBRE_CATEGORIA        VARCHAR(60),
  P_DESCRIPCION_CATEGORIA   VARCHAR(150),
  P_TIPO_CATEGORIA          VARCHAR(20),
  P_CREADO_POR              INTEGER
)
RETURNS (
  ID_CATEGORIA_OUT INTEGER
)
AS
BEGIN
  INSERT INTO CATEGORIA (
    ID_CATEGORIA,
    NOMBRE_CATEGORIA,
    DESCRIPCION_CATEGORIA,
    TIPO_CATEGORIA,
    CREADO_POR,
    MODIFICADO_POR,
    CREADO_EN,
    MODIFICADO_EN
  )
  VALUES (
    NULL, -- TR_CAT_ID genera el ID
    :P_NOMBRE_CATEGORIA,
    :P_DESCRIPCION_CATEGORIA,
    :P_TIPO_CATEGORIA,
    :P_CREADO_POR,
    :P_CREADO_POR,
    NULL, NULL -- TR_CAT_AUD setea timestamps
  )
  RETURNING ID_CATEGORIA
  INTO :ID_CATEGORIA_OUT;

  SUSPEND;
END^

-- 2) READ (uno)
CREATE OR ALTER PROCEDURE SP_CONSULTAR_CATEGORIA(
  P_ID_CATEGORIA INTEGER
)
RETURNS (
  ID_CATEGORIA           INTEGER,
  NOMBRE_CATEGORIA       VARCHAR(60),
  DESCRIPCION_CATEGORIA  VARCHAR(150),
  TIPO_CATEGORIA         VARCHAR(20),
  CREADO_POR             INTEGER,
  MODIFICADO_POR         INTEGER,
  CREADO_EN              TIMESTAMP,
  MODIFICADO_EN          TIMESTAMP
)
AS
BEGIN
  SELECT
    C.ID_CATEGORIA,
    C.NOMBRE_CATEGORIA,
    C.DESCRIPCION_CATEGORIA,
    C.TIPO_CATEGORIA,
    C.CREADO_POR,
    C.MODIFICADO_POR,
    C.CREADO_EN,
    C.MODIFICADO_EN
  FROM CATEGORIA C
  WHERE C.ID_CATEGORIA = :P_ID_CATEGORIA
  INTO
    :ID_CATEGORIA,
    :NOMBRE_CATEGORIA,
    :DESCRIPCION_CATEGORIA,
    :TIPO_CATEGORIA,
    :CREADO_POR,
    :MODIFICADO_POR,
    :CREADO_EN,
    :MODIFICADO_EN;

  SUSPEND;
END^

-- 3) READ (lista)
CREATE OR ALTER PROCEDURE SP_LISTAR_CATEGORIAS
RETURNS (
  ID_CATEGORIA      INTEGER,
  NOMBRE_CATEGORIA  VARCHAR(60),
  TIPO_CATEGORIA    VARCHAR(20)
)
AS
BEGIN
  FOR
    SELECT
      C.ID_CATEGORIA,
      C.NOMBRE_CATEGORIA,
      C.TIPO_CATEGORIA
    FROM CATEGORIA C
    INTO
      :ID_CATEGORIA,
      :NOMBRE_CATEGORIA,
      :TIPO_CATEGORIA
  DO
  BEGIN
    SUSPEND;
  END
END^

-- 4) UPDATE
CREATE OR ALTER PROCEDURE SP_ACTUALIZAR_CATEGORIA(
  P_ID_CATEGORIA          INTEGER,
  P_NOMBRE_CATEGORIA      VARCHAR(60),
  P_DESCRIPCION_CATEGORIA VARCHAR(150),
  P_TIPO_CATEGORIA        VARCHAR(20),
  P_MODIFICADO_POR        INTEGER
)
AS
BEGIN
  UPDATE CATEGORIA C
  SET
    C.NOMBRE_CATEGORIA      = :P_NOMBRE_CATEGORIA,
    C.DESCRIPCION_CATEGORIA = :P_DESCRIPCION_CATEGORIA,
    C.TIPO_CATEGORIA        = :P_TIPO_CATEGORIA,
    C.MODIFICADO_POR        = :P_MODIFICADO_POR
  WHERE C.ID_CATEGORIA = :P_ID_CATEGORIA;
END^

-- 5) DELETE 
CREATE OR ALTER PROCEDURE SP_ELIMINAR_CATEGORIA(
  P_ID_CATEGORIA INTEGER
)
AS
BEGIN
  DELETE FROM CATEGORIA
  WHERE ID_CATEGORIA = :P_ID_CATEGORIA;
END^

SET TERM ; ^