-- CRUD OBLIGACION_FIJA

SET TERM ^ ;

-- 1) CREATE
CREATE OR ALTER PROCEDURE SP_INSERTAR_OBLIGACION_FIJA(
  P_ID_SUBCATEGORIA          INTEGER,
  P_NOMBRE_OBLIGACION        VARCHAR(100),
  P_DESCRIPCION_OBLIGACION   VARCHAR(200),
  P_MONTO_FIJO_MENSUAL       DECIMAL(18,2),
  P_DIA_VENCIMIENTO          INTEGER,
  P_VIGENTE                  BOOLEAN,
  P_FECHA_INICIO             DATE,
  P_FECHA_FIN                DATE,
  P_CREADO_POR               INTEGER
)
RETURNS (
  ID_OBLIGACION_OUT INTEGER
)
AS
BEGIN
  INSERT INTO OBLIGACION_FIJA (
    ID_OBLIGACION,
    ID_SUBCATEGORIA,
    NOMBRE_OBLIGACION,
    DESCRIPCION_OBLIGACION,
    MONTO_FIJO_MENSUAL,
    DIA_VENCIMIENTO,
    VIGENTE,
    FECHA_INICIO,
    FECHA_FIN,
    CREADO_POR,
    MODIFICADO_POR,
    CREADO_EN,
    MODIFICADO_EN
  )
  VALUES (
    NULL,
    :P_ID_SUBCATEGORIA,
    :P_NOMBRE_OBLIGACION,
    :P_DESCRIPCION_OBLIGACION,
    :P_MONTO_FIJO_MENSUAL,
    :P_DIA_VENCIMIENTO,
    :P_VIGENTE,
    :P_FECHA_INICIO,
    :P_FECHA_FIN,
    :P_CREADO_POR,
    :P_CREADO_POR,
    NULL,
    NULL
  )
  RETURNING ID_OBLIGACION
  INTO :ID_OBLIGACION_OUT;

  SUSPEND;
END^

-- 2) READ uno
CREATE OR ALTER PROCEDURE SP_CONSULTAR_OBLIGACION_FIJA(
  P_ID_OBLIGACION INTEGER
)
RETURNS (
  ID_OBLIGACION            INTEGER,
  ID_SUBCATEGORIA          INTEGER,
  NOMBRE_OBLIGACION        VARCHAR(100),
  DESCRIPCION_OBLIGACION   VARCHAR(200),
  MONTO_FIJO_MENSUAL       DECIMAL(18,2),
  DIA_VENCIMIENTO          INTEGER,
  VIGENTE                  BOOLEAN,
  FECHA_INICIO             DATE,
  FECHA_FIN                DATE,
  CREADO_POR               INTEGER,
  MODIFICADO_POR           INTEGER,
  CREADO_EN                TIMESTAMP,
  MODIFICADO_EN            TIMESTAMP
)
AS
BEGIN
  SELECT
    O.ID_OBLIGACION,
    O.ID_SUBCATEGORIA,
    O.NOMBRE_OBLIGACION,
    O.DESCRIPCION_OBLIGACION,
    O.MONTO_FIJO_MENSUAL,
    O.DIA_VENCIMIENTO,
    O.VIGENTE,
    O.FECHA_INICIO,
    O.FECHA_FIN,
    O.CREADO_POR,
    O.MODIFICADO_POR,
    O.CREADO_EN,
    O.MODIFICADO_EN
  FROM OBLIGACION_FIJA O
  WHERE O.ID_OBLIGACION = :P_ID_OBLIGACION
  INTO
    :ID_OBLIGACION,
    :ID_SUBCATEGORIA,
    :NOMBRE_OBLIGACION,
    :DESCRIPCION_OBLIGACION,
    :MONTO_FIJO_MENSUAL,
    :DIA_VENCIMIENTO,
    :VIGENTE,
    :FECHA_INICIO,
    :FECHA_FIN,
    :CREADO_POR,
    :MODIFICADO_POR,
    :CREADO_EN,
    :MODIFICADO_EN;

  SUSPEND;
END^

-- 3) READ lista
CREATE OR ALTER PROCEDURE SP_LISTAR_OBLIGACIONES_FIJAS
RETURNS (
  ID_OBLIGACION            INTEGER,
  ID_SUBCATEGORIA          INTEGER,
  NOMBRE_OBLIGACION        VARCHAR(100),
  DESCRIPCION_OBLIGACION   VARCHAR(200),
  MONTO_FIJO_MENSUAL       DECIMAL(18,2),
  DIA_VENCIMIENTO          INTEGER,
  VIGENTE                  BOOLEAN,
  FECHA_INICIO             DATE,
  FECHA_FIN                DATE
)
AS
BEGIN
  FOR
    SELECT
      O.ID_OBLIGACION,
      O.ID_SUBCATEGORIA,
      O.NOMBRE_OBLIGACION,
      O.DESCRIPCION_OBLIGACION,
      O.MONTO_FIJO_MENSUAL,
      O.DIA_VENCIMIENTO,
      O.VIGENTE,
      O.FECHA_INICIO,
      O.FECHA_FIN
    FROM OBLIGACION_FIJA O
    INTO
      :ID_OBLIGACION,
      :ID_SUBCATEGORIA,
      :NOMBRE_OBLIGACION,
      :DESCRIPCION_OBLIGACION,
      :MONTO_FIJO_MENSUAL,
      :DIA_VENCIMIENTO,
      :VIGENTE,
      :FECHA_INICIO,
      :FECHA_FIN
  DO
  BEGIN
    SUSPEND;
  END
END^

-- 4) UPDATE
CREATE OR ALTER PROCEDURE SP_ACTUALIZAR_OBLIGACION_FIJA(
  P_ID_OBLIGACION            INTEGER,
  P_ID_SUBCATEGORIA          INTEGER,
  P_NOMBRE_OBLIGACION        VARCHAR(100),
  P_DESCRIPCION_OBLIGACION   VARCHAR(200),
  P_MONTO_FIJO_MENSUAL       DECIMAL(18,2),
  P_DIA_VENCIMIENTO          INTEGER,
  P_VIGENTE                  BOOLEAN,
  P_FECHA_INICIO             DATE,
  P_FECHA_FIN                DATE,
  P_MODIFICADO_POR           INTEGER
)
AS
BEGIN
  UPDATE OBLIGACION_FIJA O
  SET
    O.ID_SUBCATEGORIA        = :P_ID_SUBCATEGORIA,
    O.NOMBRE_OBLIGACION      = :P_NOMBRE_OBLIGACION,
    O.DESCRIPCION_OBLIGACION = :P_DESCRIPCION_OBLIGACION,
    O.MONTO_FIJO_MENSUAL     = :P_MONTO_FIJO_MENSUAL,
    O.DIA_VENCIMIENTO        = :P_DIA_VENCIMIENTO,
    O.VIGENTE                = :P_VIGENTE,
    O.FECHA_INICIO           = :P_FECHA_INICIO,
    O.FECHA_FIN              = :P_FECHA_FIN,
    O.MODIFICADO_POR         = :P_MODIFICADO_POR
  WHERE O.ID_OBLIGACION = :P_ID_OBLIGACION;
END^

-- 5) DELETE 
CREATE OR ALTER PROCEDURE SP_ELIMINAR_OBLIGACION_FIJA(
  P_ID_OBLIGACION   INTEGER,
  P_MODIFICADO_POR  INTEGER
)
AS
BEGIN
  UPDATE OBLIGACION_FIJA O
  SET
    O.VIGENTE        = FALSE,
    O.MODIFICADO_POR = :P_MODIFICADO_POR
  WHERE O.ID_OBLIGACION = :P_ID_OBLIGACION;
END^

SET TERM ; ^