-- CRUD TRANSACCION

SET TERM ^ ;

-- 1) CREATE
CREATE OR ALTER PROCEDURE SP_INSERTAR_TRANSACCION(
  P_ID_DETALLE        INTEGER,
  P_ANIO_TRANSACCION  INTEGER,
  P_MES_TRANSACCION   INTEGER,
  P_ID_OBLIGACION     INTEGER,
  P_TIPO_TRANSACCION  VARCHAR(20),
  P_DESCRIPCION       VARCHAR(200),
  P_MONTO             DECIMAL(18,2),
  P_FECHA_TRANSACCION DATE,
  P_METODO_PAGO       VARCHAR(30),
  P_NUMERO_FACTURA    VARCHAR(40),
  P_OBSERVACIONES     VARCHAR(200),
  P_CREADO_POR        INTEGER
)
RETURNS (
  ID_TRANSACCION_OUT INTEGER
)
AS
BEGIN
  INSERT INTO TRANSACCION (
    ID_TRANSACCION,
    ID_DETALLE,
    ANIO_TRANSACCION,
    MES_TRANSACCION,
    ID_OBLIGACION,
    TIPO_TRANSACCION,
    DESCRIPCION,
    MONTO,
    FECHA_TRANSACCION,
    METODO_PAGO,
    NUMERO_FACTURA,
    OBSERVACIONES,
    REGISTRADO_EN,
    CREADO_POR,
    MODIFICADO_POR,
    CREADO_EN,
    MODIFICADO_EN
  )
  VALUES (
    NULL, -- TR_TRA_ID genera el ID
    :P_ID_DETALLE,
    :P_ANIO_TRANSACCION,
    :P_MES_TRANSACCION,
    :P_ID_OBLIGACION,
    :P_TIPO_TRANSACCION,
    :P_DESCRIPCION,
    :P_MONTO,
    :P_FECHA_TRANSACCION,
    :P_METODO_PAGO,
    :P_NUMERO_FACTURA,
    :P_OBSERVACIONES,
    NULL, -- TR_TRA_AUD puede setear REGISTRADO_EN si viene NULL
    :P_CREADO_POR,
    :P_CREADO_POR,
    NULL, NULL -- TR_TRA_AUD setea timestamps
  )
  RETURNING ID_TRANSACCION
  INTO :ID_TRANSACCION_OUT;

  SUSPEND;
END^

-- 2) READ uno individual
CREATE OR ALTER PROCEDURE SP_CONSULTAR_TRANSACCION(
  P_ID_TRANSACCION INTEGER
)
RETURNS (
  ID_TRANSACCION     INTEGER,
  ID_DETALLE         INTEGER,
  ANIO_TRANSACCION   INTEGER,
  MES_TRANSACCION    INTEGER,
  ID_OBLIGACION      INTEGER,
  TIPO_TRANSACCION   VARCHAR(20),
  DESCRIPCION        VARCHAR(200),
  MONTO              DECIMAL(18,2),
  FECHA_TRANSACCION  DATE,
  METODO_PAGO        VARCHAR(30),
  NUMERO_FACTURA     VARCHAR(40),
  OBSERVACIONES      VARCHAR(200),
  REGISTRADO_EN      TIMESTAMP,
  CREADO_POR         INTEGER,
  MODIFICADO_POR     INTEGER,
  CREADO_EN          TIMESTAMP,
  MODIFICADO_EN      TIMESTAMP
)
AS
BEGIN
  SELECT
    T.ID_TRANSACCION,
    T.ID_DETALLE,
    T.ANIO_TRANSACCION,
    T.MES_TRANSACCION,
    T.ID_OBLIGACION,
    T.TIPO_TRANSACCION,
    T.DESCRIPCION,
    T.MONTO,
    T.FECHA_TRANSACCION,
    T.METODO_PAGO,
    T.NUMERO_FACTURA,
    T.OBSERVACIONES,
    T.REGISTRADO_EN,
    T.CREADO_POR,
    T.MODIFICADO_POR,
    T.CREADO_EN,
    T.MODIFICADO_EN
  FROM TRANSACCION T
  WHERE T.ID_TRANSACCION = :P_ID_TRANSACCION
  INTO
    :ID_TRANSACCION,
    :ID_DETALLE,
    :ANIO_TRANSACCION,
    :MES_TRANSACCION,
    :ID_OBLIGACION,
    :TIPO_TRANSACCION,
    :DESCRIPCION,
    :MONTO,
    :FECHA_TRANSACCION,
    :METODO_PAGO,
    :NUMERO_FACTURA,
    :OBSERVACIONES,
    :REGISTRADO_EN,
    :CREADO_POR,
    :MODIFICADO_POR,
    :CREADO_EN,
    :MODIFICADO_EN;

  SUSPEND;
END^

-- 3) READ (lista por presupuesto_detalle + año/mes + tipo opcional)
CREATE OR ALTER PROCEDURE SP_LISTAR_TRANSACCIONES(
  P_ID_DETALLE       INTEGER,
  P_ANIO_TRANSACCION INTEGER,
  P_MES_TRANSACCION  INTEGER,
  P_TIPO_TRANSACCION VARCHAR(20)
)
RETURNS (
  ID_TRANSACCION     INTEGER,
  ID_DETALLE         INTEGER,
  ANIO_TRANSACCION   INTEGER,
  MES_TRANSACCION    INTEGER,
  ID_OBLIGACION      INTEGER,
  TIPO_TRANSACCION   VARCHAR(20),
  DESCRIPCION        VARCHAR(200),
  MONTO              DECIMAL(18,2),
  FECHA_TRANSACCION  DATE,
  METODO_PAGO        VARCHAR(30),
  NUMERO_FACTURA     VARCHAR(40),
  OBSERVACIONES      VARCHAR(200)
)
AS
BEGIN
  FOR
    SELECT
      T.ID_TRANSACCION,
      T.ID_DETALLE,
      T.ANIO_TRANSACCION,
      T.MES_TRANSACCION,
      T.ID_OBLIGACION,
      T.TIPO_TRANSACCION,
      T.DESCRIPCION,
      T.MONTO,
      T.FECHA_TRANSACCION,
      T.METODO_PAGO,
      T.NUMERO_FACTURA,
      T.OBSERVACIONES
    FROM TRANSACCION T
    WHERE T.ID_DETALLE = :P_ID_DETALLE
      AND T.ANIO_TRANSACCION = :P_ANIO_TRANSACCION
      AND T.MES_TRANSACCION  = :P_MES_TRANSACCION
      AND ( :P_TIPO_TRANSACCION IS NULL OR T.TIPO_TRANSACCION = :P_TIPO_TRANSACCION )
    INTO
      :ID_TRANSACCION,
      :ID_DETALLE,
      :ANIO_TRANSACCION,
      :MES_TRANSACCION,
      :ID_OBLIGACION,
      :TIPO_TRANSACCION,
      :DESCRIPCION,
      :MONTO,
      :FECHA_TRANSACCION,
      :METODO_PAGO,
      :NUMERO_FACTURA,
      :OBSERVACIONES
  DO
  BEGIN
    SUSPEND;
  END
END^

-- 4) UPDATE
CREATE OR ALTER PROCEDURE SP_ACTUALIZAR_TRANSACCION(
  P_ID_TRANSACCION   INTEGER,
  P_ID_DETALLE       INTEGER,
  P_ANIO_TRANSACCION INTEGER,
  P_MES_TRANSACCION  INTEGER,
  P_ID_OBLIGACION    INTEGER,
  P_TIPO_TRANSACCION VARCHAR(20),
  P_DESCRIPCION      VARCHAR(200),
  P_MONTO            DECIMAL(18,2),
  P_FECHA_TRANSACCION DATE,
  P_METODO_PAGO      VARCHAR(30),
  P_NUMERO_FACTURA   VARCHAR(40),
  P_OBSERVACIONES    VARCHAR(200),
  P_MODIFICADO_POR   INTEGER
)
AS
BEGIN
  UPDATE TRANSACCION T
  SET
    T.ID_DETALLE        = :P_ID_DETALLE,
    T.ANIO_TRANSACCION  = :P_ANIO_TRANSACCION,
    T.MES_TRANSACCION   = :P_MES_TRANSACCION,
    T.ID_OBLIGACION     = :P_ID_OBLIGACION,
    T.TIPO_TRANSACCION  = :P_TIPO_TRANSACCION,
    T.DESCRIPCION       = :P_DESCRIPCION,
    T.MONTO             = :P_MONTO,
    T.FECHA_TRANSACCION = :P_FECHA_TRANSACCION,
    T.METODO_PAGO       = :P_METODO_PAGO,
    T.NUMERO_FACTURA    = :P_NUMERO_FACTURA,
    T.OBSERVACIONES     = :P_OBSERVACIONES,
    T.MODIFICADO_POR    = :P_MODIFICADO_POR
  WHERE T.ID_TRANSACCION = :P_ID_TRANSACCION;
END^

-- 5) DELETE
CREATE OR ALTER PROCEDURE SP_ELIMINAR_TRANSACCION(
  P_ID_TRANSACCION INTEGER
)
AS
BEGIN
  DELETE FROM TRANSACCION T
  WHERE T.ID_TRANSACCION = :P_ID_TRANSACCION;
END^

SET TERM ; ^