-- CRUD SUBCATEGORIA

SET TERM ^ ;

-- 1) CREATE
CREATE OR ALTER PROCEDURE SP_INSERTAR_SUBCATEGORIA(
  P_ID_CATEGORIA            INTEGER,
  P_NOMBRE_SUBCATEGORIA     VARCHAR(60),
  P_DESCRIPCION_SUBCATEGORIA VARCHAR(150),
  P_ACTIVA                  BOOLEAN,
  P_ES_POR_DEFECTO          BOOLEAN,
  P_CREADO_POR              INTEGER
)
RETURNS (
  ID_SUBCATEGORIA_OUT INTEGER
)
AS
BEGIN
  INSERT INTO SUBCATEGORIA (
    ID_SUBCATEGORIA,
    ID_CATEGORIA,
    NOMBRE_SUBCATEGORIA,
    DESCRIPCION_SUBCATEGORIA,
    ACTIVA,
    ES_POR_DEFECTO,
    CREADO_POR,
    MODIFICADO_POR,
    CREADO_EN,
    MODIFICADO_EN
  )
  VALUES (
    NULL, -- TR_SUB_ID genera el ID
    :P_ID_CATEGORIA,
    :P_NOMBRE_SUBCATEGORIA,
    :P_DESCRIPCION_SUBCATEGORIA,
    COALESCE(:P_ACTIVA, TRUE),
    COALESCE(:P_ES_POR_DEFECTO, FALSE),
    :P_CREADO_POR,
    :P_CREADO_POR,
    NULL, NULL -- TR_SUB_AUD setea timestamps
  )
  RETURNING ID_SUBCATEGORIA
  INTO :ID_SUBCATEGORIA_OUT;

  SUSPEND;
END^

-- 2) READ uno individual 
CREATE OR ALTER PROCEDURE SP_CONSULTAR_SUBCATEGORIA(
  P_ID_SUBCATEGORIA INTEGER
)
RETURNS (
  ID_SUBCATEGORIA            INTEGER,
  ID_CATEGORIA               INTEGER,
  NOMBRE_SUBCATEGORIA        VARCHAR(60),
  DESCRIPCION_SUBCATEGORIA   VARCHAR(150),
  ACTIVA                     BOOLEAN,
  ES_POR_DEFECTO             BOOLEAN,
  CREADO_POR                 INTEGER,
  MODIFICADO_POR             INTEGER,
  CREADO_EN                  TIMESTAMP,
  MODIFICADO_EN              TIMESTAMP
)
AS
BEGIN
  SELECT
    S.ID_SUBCATEGORIA,
    S.ID_CATEGORIA,
    S.NOMBRE_SUBCATEGORIA,
    S.DESCRIPCION_SUBCATEGORIA,
    S.ACTIVA,
    S.ES_POR_DEFECTO,
    S.CREADO_POR,
    S.MODIFICADO_POR,
    S.CREADO_EN,
    S.MODIFICADO_EN
  FROM SUBCATEGORIA S
  WHERE S.ID_SUBCATEGORIA = :P_ID_SUBCATEGORIA
  INTO
    :ID_SUBCATEGORIA,
    :ID_CATEGORIA,
    :NOMBRE_SUBCATEGORIA,
    :DESCRIPCION_SUBCATEGORIA,
    :ACTIVA,
    :ES_POR_DEFECTO,
    :CREADO_POR,
    :MODIFICADO_POR,
    :CREADO_EN,
    :MODIFICADO_EN;

  SUSPEND;
END^

-- 3) READ (lista por categoría)
CREATE OR ALTER PROCEDURE SP_LISTAR_SUBC_POR_CATEGORIA(
  P_ID_CATEGORIA INTEGER
)
RETURNS (
  ID_SUBCATEGORIA          INTEGER,
  ID_CATEGORIA             INTEGER,
  NOMBRE_SUBCATEGORIA      VARCHAR(60),
  ACTIVA                   BOOLEAN,
  ES_POR_DEFECTO           BOOLEAN
)
AS
BEGIN
  FOR
    SELECT
      S.ID_SUBCATEGORIA,
      S.ID_CATEGORIA,
      S.NOMBRE_SUBCATEGORIA,
      S.ACTIVA,
      S.ES_POR_DEFECTO
    FROM SUBCATEGORIA S
    WHERE S.ID_CATEGORIA = :P_ID_CATEGORIA
    INTO
      :ID_SUBCATEGORIA,
      :ID_CATEGORIA,
      :NOMBRE_SUBCATEGORIA,
      :ACTIVA,
      :ES_POR_DEFECTO
  DO
  BEGIN
    SUSPEND;
  END
END^

-- 4) UPDATE
CREATE OR ALTER PROCEDURE SP_ACTUALIZAR_SUBCATEGORIA(
  P_ID_SUBCATEGORIA          INTEGER,
  P_ID_CATEGORIA             INTEGER,
  P_NOMBRE_SUBCATEGORIA      VARCHAR(60),
  P_DESCRIPCION_SUBCATEGORIA VARCHAR(150),
  P_ACTIVA                   BOOLEAN,
  P_ES_POR_DEFECTO           BOOLEAN,
  P_MODIFICADO_POR           INTEGER
)
AS
BEGIN
  UPDATE SUBCATEGORIA S
  SET
    S.ID_CATEGORIA             = :P_ID_CATEGORIA,
    S.NOMBRE_SUBCATEGORIA      = :P_NOMBRE_SUBCATEGORIA,
    S.DESCRIPCION_SUBCATEGORIA = :P_DESCRIPCION_SUBCATEGORIA,
    S.ACTIVA                   = :P_ACTIVA,
    S.ES_POR_DEFECTO           = :P_ES_POR_DEFECTO,
    S.MODIFICADO_POR           = :P_MODIFICADO_POR
  WHERE S.ID_SUBCATEGORIA = :P_ID_SUBCATEGORIA;
END^

-- 5) DELETE 
CREATE OR ALTER PROCEDURE SP_ELIMINAR_SUBCATEGORIA(
  P_ID_SUBCATEGORIA INTEGER,
  P_MODIFICADO_POR  INTEGER
)
AS
BEGIN
  UPDATE SUBCATEGORIA S
  SET
    S.ACTIVA = FALSE,
    S.MODIFICADO_POR = :P_MODIFICADO_POR
  WHERE S.ID_SUBCATEGORIA = :P_ID_SUBCATEGORIA;
END^

SET TERM ; ^