-- CRUD USUARIO

SET TERM ^ ;

-- 1) CREATE
CREATE OR ALTER PROCEDURE SP_INSERTAR_USUARIO(
  P_PRIMER_NOMBRE      VARCHAR(80),
  P_SEGUNDO_NOMBRE     VARCHAR(80),
  P_PRIMER_APELLIDO    VARCHAR(80),
  P_SEGUNDO_APELLIDO   VARCHAR(80),
  P_CORREO             VARCHAR(120),
  P_CLAVE              VARCHAR(255),
  P_SALARIO_MENSUAL    DECIMAL(18,2),
  P_CREADO_POR         INTEGER
)
RETURNS (
  ID_USUARIO_OUT INTEGER
)
AS
BEGIN
  INSERT INTO USUARIO (
    ID_USUARIO,
    PRIMER_NOMBRE,
    SEGUNDO_NOMBRE,
    PRIMER_APELLIDO,
    SEGUNDO_APELLIDO,
    CORREO_ELECTRONICO,
    CLAVE,
    SALARIO_MENSUAL,
    ESTADO_ACTIVO,
    CREADO_POR,
    MODIFICADO_POR,
    CREADO_EN,
    MODIFICADO_EN
  )
  VALUES (
    NULL,
    :P_PRIMER_NOMBRE,
    :P_SEGUNDO_NOMBRE,
    :P_PRIMER_APELLIDO,
    :P_SEGUNDO_APELLIDO,
    :P_CORREO,
    :P_CLAVE,
    :P_SALARIO_MENSUAL,
    TRUE,
    :P_CREADO_POR,
    :P_CREADO_POR,
    NULL, NULL
  )
  RETURNING ID_USUARIO
  INTO :ID_USUARIO_OUT;

  SUSPEND;
END^

-- 2) READ uno individual
CREATE OR ALTER PROCEDURE SP_CONSULTAR_USUARIO(
  P_ID_USUARIO INTEGER
)
RETURNS (
  ID_USUARIO          INTEGER,
  PRIMER_NOMBRE       VARCHAR(80),
  SEGUNDO_NOMBRE      VARCHAR(80),
  PRIMER_APELLIDO     VARCHAR(80),
  SEGUNDO_APELLIDO    VARCHAR(80),
  CORREO_ELECTRONICO  VARCHAR(120),
  CLAVE               VARCHAR(255),
  SALARIO_MENSUAL     DECIMAL(18,2),
  ESTADO_ACTIVO       BOOLEAN,
  CREADO_POR          INTEGER,
  MODIFICADO_POR      INTEGER,
  CREADO_EN           TIMESTAMP,
  MODIFICADO_EN       TIMESTAMP
)
AS
BEGIN
  SELECT
    U.ID_USUARIO,
    U.PRIMER_NOMBRE,
    U.SEGUNDO_NOMBRE,
    U.PRIMER_APELLIDO,
    U.SEGUNDO_APELLIDO,
    U.CORREO_ELECTRONICO,
    U.CLAVE,
    U.SALARIO_MENSUAL,
    U.ESTADO_ACTIVO,
    U.CREADO_POR,
    U.MODIFICADO_POR,
    U.CREADO_EN,
    U.MODIFICADO_EN
  FROM USUARIO U
  WHERE U.ID_USUARIO = :P_ID_USUARIO
  INTO
    :ID_USUARIO,
    :PRIMER_NOMBRE,
    :SEGUNDO_NOMBRE,
    :PRIMER_APELLIDO,
    :SEGUNDO_APELLIDO,
    :CORREO_ELECTRONICO,
    :CLAVE,
    :SALARIO_MENSUAL,
    :ESTADO_ACTIVO,
    :CREADO_POR,
    :MODIFICADO_POR,
    :CREADO_EN,
    :MODIFICADO_EN;

  SUSPEND;
END^

-- 3) READ (listar por usuario)
CREATE OR ALTER PROCEDURE SP_LISTAR_USUARIOS
RETURNS (
  ID_USUARIO          INTEGER,
  PRIMER_NOMBRE       VARCHAR(80),
  PRIMER_APELLIDO     VARCHAR(80),
  CORREO_ELECTRONICO  VARCHAR(120),
  SALARIO_MENSUAL     DECIMAL(18,2),
  ESTADO_ACTIVO       BOOLEAN
)
AS
BEGIN
  FOR
    SELECT
      U.ID_USUARIO,
      U.PRIMER_NOMBRE,
      U.PRIMER_APELLIDO,
      U.CORREO_ELECTRONICO,
      U.SALARIO_MENSUAL,
      U.ESTADO_ACTIVO
    FROM USUARIO U
    INTO
      :ID_USUARIO,
      :PRIMER_NOMBRE,
      :PRIMER_APELLIDO,
      :CORREO_ELECTRONICO,
      :SALARIO_MENSUAL,
      :ESTADO_ACTIVO
  DO
  BEGIN
    SUSPEND;
  END
END^

-- 4) UPDATE
CREATE OR ALTER PROCEDURE SP_ACTUALIZAR_USUARIO(
  P_ID_USUARIO         INTEGER,
  P_PRIMER_NOMBRE      VARCHAR(80),
  P_SEGUNDO_NOMBRE     VARCHAR(80),
  P_PRIMER_APELLIDO    VARCHAR(80),
  P_SEGUNDO_APELLIDO   VARCHAR(80),
  P_CORREO             VARCHAR(120),
  P_CLAVE              VARCHAR(255),
  P_SALARIO_MENSUAL    DECIMAL(18,2),
  P_ESTADO_ACTIVO      BOOLEAN,
  P_MODIFICADO_POR     INTEGER
)
AS
BEGIN
  UPDATE USUARIO U
  SET
    U.PRIMER_NOMBRE      = :P_PRIMER_NOMBRE,
    U.SEGUNDO_NOMBRE     = :P_SEGUNDO_NOMBRE,
    U.PRIMER_APELLIDO    = :P_PRIMER_APELLIDO,
    U.SEGUNDO_APELLIDO   = :P_SEGUNDO_APELLIDO,
    U.CORREO_ELECTRONICO = :P_CORREO,
    U.CLAVE              = :P_CLAVE,
    U.SALARIO_MENSUAL    = :P_SALARIO_MENSUAL,
    U.ESTADO_ACTIVO      = :P_ESTADO_ACTIVO,
    U.MODIFICADO_POR     = :P_MODIFICADO_POR
  WHERE U.ID_USUARIO = :P_ID_USUARIO;
END^

-- 5) DELETE
CREATE OR ALTER PROCEDURE SP_ELIMINAR_USUARIO(
  P_ID_USUARIO     INTEGER,
  P_MODIFICADO_POR INTEGER
)
AS
BEGIN
  UPDATE USUARIO U
  SET
    U.ESTADO_ACTIVO  = FALSE,
    U.MODIFICADO_POR = :P_MODIFICADO_POR
  WHERE U.ID_USUARIO = :P_ID_USUARIO;
END^

SET TERM ; ^