-- CRUD PRESUPUESTO_DETALLE

SET TERM ^ ;

-- 1) CREATE
CREATE OR ALTER PROCEDURE SP_INSERTAR_PRES_DET(
  P_ID_PRESUPUESTO          INTEGER,
  P_ID_SUBCATEGORIA         INTEGER,
  P_MONTO_MENSUAL_ASIGNADO  DECIMAL(18,2),
  P_OBSERVACIONES           VARCHAR(200),
  P_CREADO_POR              INTEGER
)
RETURNS (
  ID_DETALLE_OUT INTEGER
)
AS
BEGIN
  INSERT INTO PRESUPUESTO_DETALLE (
    ID_DETALLE,
    ID_PRESUPUESTO,
    ID_SUBCATEGORIA,
    MONTO_MENSUAL_ASIGNADO,
    OBSERVACIONES,
    CREADO_POR,
    MODIFICADO_POR,
    CREADO_EN,
    MODIFICADO_EN
  )
  VALUES (
    NULL, -- TR_DET_ID genera el ID
    :P_ID_PRESUPUESTO,
    :P_ID_SUBCATEGORIA,
    :P_MONTO_MENSUAL_ASIGNADO,
    :P_OBSERVACIONES,
    :P_CREADO_POR,
    :P_CREADO_POR,
    NULL, NULL -- TR_DET_AUD setea timestamps
  )
  RETURNING ID_DETALLE
  INTO :ID_DETALLE_OUT;

  SUSPEND;
END^

-- 2) READ uno individual
CREATE OR ALTER PROCEDURE SP_CONSULTAR_PRES_DET(
  P_ID_DETALLE INTEGER
)
RETURNS (
  ID_DETALLE              INTEGER,
  ID_PRESUPUESTO          INTEGER,
  ID_SUBCATEGORIA         INTEGER,
  MONTO_MENSUAL_ASIGNADO  DECIMAL(18,2),
  OBSERVACIONES           VARCHAR(200),
  CREADO_POR              INTEGER,
  MODIFICADO_POR          INTEGER,
  CREADO_EN               TIMESTAMP,
  MODIFICADO_EN           TIMESTAMP
)
AS
BEGIN
  SELECT
    D.ID_DETALLE,
    D.ID_PRESUPUESTO,
    D.ID_SUBCATEGORIA,
    D.MONTO_MENSUAL_ASIGNADO,
    D.OBSERVACIONES,
    D.CREADO_POR,
    D.MODIFICADO_POR,
    D.CREADO_EN,
    D.MODIFICADO_EN
  FROM PRESUPUESTO_DETALLE D
  WHERE D.ID_DETALLE = :P_ID_DETALLE
  INTO
    :ID_DETALLE,
    :ID_PRESUPUESTO,
    :ID_SUBCATEGORIA,
    :MONTO_MENSUAL_ASIGNADO,
    :OBSERVACIONES,
    :CREADO_POR,
    :MODIFICADO_POR,
    :CREADO_EN,
    :MODIFICADO_EN;

  SUSPEND;
END^

-- 3) READ (lista por presupuesto)
CREATE OR ALTER PROCEDURE SP_LISTAR_PRES_DET(
  P_ID_PRESUPUESTO INTEGER
)
RETURNS (
  ID_DETALLE              INTEGER,
  ID_PRESUPUESTO          INTEGER,
  ID_SUBCATEGORIA         INTEGER,
  MONTO_MENSUAL_ASIGNADO  DECIMAL(18,2),
  OBSERVACIONES           VARCHAR(200)
)
AS
BEGIN
  FOR
    SELECT
      D.ID_DETALLE,
      D.ID_PRESUPUESTO,
      D.ID_SUBCATEGORIA,
      D.MONTO_MENSUAL_ASIGNADO,
      D.OBSERVACIONES
    FROM PRESUPUESTO_DETALLE D
    WHERE D.ID_PRESUPUESTO = :P_ID_PRESUPUESTO
    INTO
      :ID_DETALLE,
      :ID_PRESUPUESTO,
      :ID_SUBCATEGORIA,
      :MONTO_MENSUAL_ASIGNADO,
      :OBSERVACIONES
  DO
  BEGIN
    SUSPEND;
  END
END^

-- 4) UPDATE
CREATE OR ALTER PROCEDURE SP_ACTUALIZAR_PRES_DET(
  P_ID_DETALLE             INTEGER,
  P_ID_PRESUPUESTO         INTEGER,
  P_ID_SUBCATEGORIA        INTEGER,
  P_MONTO_MENSUAL_ASIGNADO DECIMAL(18,2),
  P_OBSERVACIONES          VARCHAR(200),
  P_MODIFICADO_POR         INTEGER
)
AS
BEGIN
  UPDATE PRESUPUESTO_DETALLE D
  SET
    D.ID_PRESUPUESTO         = :P_ID_PRESUPUESTO,
    D.ID_SUBCATEGORIA        = :P_ID_SUBCATEGORIA,
    D.MONTO_MENSUAL_ASIGNADO = :P_MONTO_MENSUAL_ASIGNADO,
    D.OBSERVACIONES          = :P_OBSERVACIONES,
    D.MODIFICADO_POR         = :P_MODIFICADO_POR
  WHERE D.ID_DETALLE = :P_ID_DETALLE;
END^

-- 5) DELETE
CREATE OR ALTER PROCEDURE SP_ELIMINAR_PRES_DET(
  P_ID_DETALLE INTEGER
)
AS
BEGIN
  DELETE FROM PRESUPUESTO_DETALLE D
  WHERE D.ID_DETALLE = :P_ID_DETALLE;
END^

SET TERM ; ^