-- CRUD PRESUPUESTO

SET TERM ^ ;

-- 1) CREATE
CREATE OR ALTER PROCEDURE SP_INSERTAR_PRESUPUESTO(
  P_ID_USUARIO                    INTEGER,
  P_NOMBRE_PRESUPUESTO            VARCHAR(120),
  P_ANIO_INICIO                   INTEGER,
  P_MES_INICIO                    INTEGER,
  P_ANIO_FIN                      INTEGER,
  P_MES_FIN                       INTEGER,
  P_TOTAL_INGRESOS_PLANIFICADOS   DECIMAL(18,2),
  P_TOTAL_GASTOS_PLANIFICADOS     DECIMAL(18,2),
  P_TOTAL_AHORRO_PLANIFICADO      DECIMAL(18,2),
  P_ESTADO_PRESUPUESTO            VARCHAR(20),
  P_CREADO_POR                    INTEGER
)
RETURNS (
  ID_PRESUPUESTO_OUT INTEGER
)
AS
BEGIN
  INSERT INTO PRESUPUESTO (
    ID_PRESUPUESTO,
    ID_USUARIO,
    NOMBRE_PRESUPUESTO,
    ANIO_INICIO,
    MES_INICIO,
    ANIO_FIN,
    MES_FIN,
    TOTAL_INGRESOS_PLANIFICADOS,
    TOTAL_GASTOS_PLANIFICADOS,
    TOTAL_AHORRO_PLANIFICADO,
    CREADO_EN,
    ESTADO_PRESUPUESTO,
    CREADO_POR,
    MODIFICADO_POR,
    MODIFICADO_EN
  )
  VALUES (
    NULL, -- TR_PRE_ID genera el ID
    :P_ID_USUARIO,
    :P_NOMBRE_PRESUPUESTO,
    :P_ANIO_INICIO,
    :P_MES_INICIO,
    :P_ANIO_FIN,
    :P_MES_FIN,
    :P_TOTAL_INGRESOS_PLANIFICADOS,
    :P_TOTAL_GASTOS_PLANIFICADOS,
    :P_TOTAL_AHORRO_PLANIFICADO,
    NULL, -- TR_PRE_AUD setea CREADO_EN / MODIFICADO_EN
    :P_ESTADO_PRESUPUESTO,
    :P_CREADO_POR,
    :P_CREADO_POR,
    NULL
  )
  RETURNING ID_PRESUPUESTO
  INTO :ID_PRESUPUESTO_OUT;

  SUSPEND;
END^

-- 2) READ uno individual
CREATE OR ALTER PROCEDURE SP_CONSULTAR_PRESUPUESTO(
  P_ID_PRESUPUESTO INTEGER
)
RETURNS (
  ID_PRESUPUESTO                  INTEGER,
  ID_USUARIO                      INTEGER,
  NOMBRE_PRESUPUESTO              VARCHAR(120),
  ANIO_INICIO                     INTEGER,
  MES_INICIO                      INTEGER,
  ANIO_FIN                        INTEGER,
  MES_FIN                         INTEGER,
  TOTAL_INGRESOS_PLANIFICADOS     DECIMAL(18,2),
  TOTAL_GASTOS_PLANIFICADOS       DECIMAL(18,2),
  TOTAL_AHORRO_PLANIFICADO        DECIMAL(18,2),
  CREADO_EN                       TIMESTAMP,
  ESTADO_PRESUPUESTO              VARCHAR(20),
  CREADO_POR                      INTEGER,
  MODIFICADO_POR                  INTEGER,
  MODIFICADO_EN                   TIMESTAMP
)
AS
BEGIN
  SELECT
    P.ID_PRESUPUESTO,
    P.ID_USUARIO,
    P.NOMBRE_PRESUPUESTO,
    P.ANIO_INICIO,
    P.MES_INICIO,
    P.ANIO_FIN,
    P.MES_FIN,
    P.TOTAL_INGRESOS_PLANIFICADOS,
    P.TOTAL_GASTOS_PLANIFICADOS,
    P.TOTAL_AHORRO_PLANIFICADO,
    P.CREADO_EN,
    P.ESTADO_PRESUPUESTO,
    P.CREADO_POR,
    P.MODIFICADO_POR,
    P.MODIFICADO_EN
  FROM PRESUPUESTO P
  WHERE P.ID_PRESUPUESTO = :P_ID_PRESUPUESTO
  INTO
    :ID_PRESUPUESTO,
    :ID_USUARIO,
    :NOMBRE_PRESUPUESTO,
    :ANIO_INICIO,
    :MES_INICIO,
    :ANIO_FIN,
    :MES_FIN,
    :TOTAL_INGRESOS_PLANIFICADOS,
    :TOTAL_GASTOS_PLANIFICADOS,
    :TOTAL_AHORRO_PLANIFICADO,
    :CREADO_EN,
    :ESTADO_PRESUPUESTO,
    :CREADO_POR,
    :MODIFICADO_POR,
    :MODIFICADO_EN;

  SUSPEND;
END^

-- 3) READ (lista por presupuesto)
CREATE OR ALTER PROCEDURE SP_LISTAR_PRESUPUESTOS
RETURNS (
  ID_PRESUPUESTO        INTEGER,
  ID_USUARIO            INTEGER,
  NOMBRE_PRESUPUESTO    VARCHAR(120),
  ANIO_INICIO           INTEGER,
  MES_INICIO            INTEGER,
  ANIO_FIN              INTEGER,
  MES_FIN               INTEGER,
  ESTADO_PRESUPUESTO    VARCHAR(20)
)
AS
BEGIN
  FOR
    SELECT
      P.ID_PRESUPUESTO,
      P.ID_USUARIO,
      P.NOMBRE_PRESUPUESTO,
      P.ANIO_INICIO,
      P.MES_INICIO,
      P.ANIO_FIN,
      P.MES_FIN,
      P.ESTADO_PRESUPUESTO
    FROM PRESUPUESTO P
    INTO
      :ID_PRESUPUESTO,
      :ID_USUARIO,
      :NOMBRE_PRESUPUESTO,
      :ANIO_INICIO,
      :MES_INICIO,
      :ANIO_FIN,
      :MES_FIN,
      :ESTADO_PRESUPUESTO
  DO
  BEGIN
    SUSPEND;
  END
END^

-- 4) UPDATE
CREATE OR ALTER PROCEDURE SP_ACTUALIZAR_PRESUPUESTO(
  P_ID_PRESUPUESTO               INTEGER,
  P_ID_USUARIO                   INTEGER,
  P_NOMBRE_PRESUPUESTO           VARCHAR(120),
  P_ANIO_INICIO                  INTEGER,
  P_MES_INICIO                   INTEGER,
  P_ANIO_FIN                     INTEGER,
  P_MES_FIN                      INTEGER,
  P_TOTAL_INGRESOS_PLANIFICADOS  DECIMAL(18,2),
  P_TOTAL_GASTOS_PLANIFICADOS    DECIMAL(18,2),
  P_TOTAL_AHORRO_PLANIFICADO     DECIMAL(18,2),
  P_ESTADO_PRESUPUESTO           VARCHAR(20),
  P_MODIFICADO_POR               INTEGER
)
AS
BEGIN
  UPDATE PRESUPUESTO P
  SET
    P.ID_USUARIO                    = :P_ID_USUARIO,
    P.NOMBRE_PRESUPUESTO            = :P_NOMBRE_PRESUPUESTO,
    P.ANIO_INICIO                   = :P_ANIO_INICIO,
    P.MES_INICIO                    = :P_MES_INICIO,
    P.ANIO_FIN                      = :P_ANIO_FIN,
    P.MES_FIN                       = :P_MES_FIN,
    P.TOTAL_INGRESOS_PLANIFICADOS   = :P_TOTAL_INGRESOS_PLANIFICADOS,
    P.TOTAL_GASTOS_PLANIFICADOS     = :P_TOTAL_GASTOS_PLANIFICADOS,
    P.TOTAL_AHORRO_PLANIFICADO      = :P_TOTAL_AHORRO_PLANIFICADO,
    P.ESTADO_PRESUPUESTO            = :P_ESTADO_PRESUPUESTO,
    P.MODIFICADO_POR                = :P_MODIFICADO_POR
  WHERE P.ID_PRESUPUESTO = :P_ID_PRESUPUESTO;
END^

-- 5) DELETE 
CREATE OR ALTER PROCEDURE SP_ELIMINAR_PRESUPUESTO(
  P_ID_PRESUPUESTO  INTEGER,
  P_MODIFICADO_POR  INTEGER
)
AS
BEGIN
  UPDATE PRESUPUESTO P
  SET
    P.ESTADO_PRESUPUESTO = 'inactivo',
    P.MODIFICADO_POR     = :P_MODIFICADO_POR
  WHERE P.ID_PRESUPUESTO = :P_ID_PRESUPUESTO;
END^

SET TERM ; ^