
-- 1) USUARIOS 
INSERT INTO USUARIO (
  ID_USUARIO,
  PRIMER_NOMBRE, SEGUNDO_NOMBRE,
  PRIMER_APELLIDO, SEGUNDO_APELLIDO,
  CORREO_ELECTRONICO, CLAVE,
  SALARIO_MENSUAL, ESTADO_ACTIVO,
  CREADO_POR, MODIFICADO_POR,
  CREADO_EN, MODIFICADO_EN
) VALUES (NULL,'Ana','Gabriela','Valle','Monges','ana@test.com','hash1',24000,TRUE,1,1,NULL,NULL);

INSERT INTO USUARIO VALUES (NULL,'Brayan','Omar','Pinel','Martinez','brayan@test.com','hash2',18000,TRUE,1,1,NULL,NULL);
INSERT INTO USUARIO VALUES (NULL,'Ashlee','Gabriela','Rodriguez','Bardales','ashlee@test.com','hash3',16500,TRUE,1,1,NULL,NULL);
INSERT INTO USUARIO VALUES (NULL,'Alejandra','Dennisse','Mejia','Paz','alejandra@test.com','hash4',19500,TRUE,1,1,NULL,NULL);
INSERT INTO USUARIO VALUES (NULL,'Emir','Abercio','Maldonado','Coto','emir@test.com','hash5',20000,TRUE,1,1,NULL,NULL);
INSERT INTO USUARIO VALUES (NULL,'Dulce','Maria','Robles','Chinchilla','dulce@test.com','hash6',21000,TRUE,1,1,NULL,NULL);
INSERT INTO USUARIO VALUES (NULL,'Jennifer','Alexandra','Valle','Flores','jennifer@test.com','hash7',12000,TRUE,1,1,NULL,NULL);
INSERT INTO USUARIO VALUES (NULL,'Adriana','Victoria','Tax','Monges','adriana@test.com','hash8',32000,TRUE,1,1,NULL,NULL);
INSERT INTO USUARIO VALUES (NULL,'Alma','Fabiola','Bardales','Bardales','alma@test.com','hash9',17000,TRUE,1,1,NULL,NULL);
INSERT INTO USUARIO VALUES (NULL,'Roger','Josue','Gomez','Valle','roger@test.com','hash10',28000,TRUE,1,1,NULL,NULL);
INSERT INTO USUARIO VALUES (NULL,'Jheison','Estuardo','Ruiz','Zaldivar','jheison@test.com','hash11',15500,TRUE,1,1,NULL,NULL);
INSERT INTO USUARIO VALUES (NULL,'Arturo','Josue','Padilla','Madrid','arturo@test.com','hash12',24000,TRUE,1,1,NULL,NULL);
INSERT INTO USUARIO VALUES (NULL,'Julian','Eduardo','Pacheco','Murillo','julian@test.com','hash13',26000,TRUE,1,1,NULL,NULL);


-- 2) CATEGORÍAS ( ingreso, gasto y ahorro)

INSERT INTO CATEGORIA (
  ID_CATEGORIA, NOMBRE_CATEGORIA, DESCRIPCION_CATEGORIA, TIPO_CATEGORIA,
  CREADO_POR, MODIFICADO_POR, CREADO_EN, MODIFICADO_EN
) VALUES (NULL,'Ingresos','Entradas de dinero','ingreso',1,1,NULL,NULL);
INSERT INTO CATEGORIA VALUES (NULL,'Gastos','Salidas de dinero','gasto',1,1,NULL,NULL);
INSERT INTO CATEGORIA VALUES (NULL,'Ahorro','Aportes de ahorro','ahorro',1,1,NULL,NULL);


-- 3) SUBCATEGORÍAS ESPECÍFICAS

-- Ingresos
INSERT INTO SUBCATEGORIA VALUES (
  NULL,
  (SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE_CATEGORIA='Ingresos'),
  'Salario Base','Ingreso mensual',TRUE,TRUE,1,1,NULL,NULL
);
-- Gastos
INSERT INTO SUBCATEGORIA VALUES (NULL,(SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE_CATEGORIA='Gastos'),'Alquiler','Pago vivienda',TRUE,FALSE,1,1,NULL,NULL);
INSERT INTO SUBCATEGORIA VALUES (NULL,(SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE_CATEGORIA='Gastos'),'Energía Eléctrica','Recibo luz',TRUE,FALSE,1,1,NULL,NULL);
INSERT INTO SUBCATEGORIA VALUES (NULL,(SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE_CATEGORIA='Gastos'),'Internet','Servicio internet',TRUE,FALSE,1,1,NULL,NULL);
INSERT INTO SUBCATEGORIA VALUES (NULL,(SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE_CATEGORIA='Gastos'),'Supermercado','Compras hogar',TRUE,FALSE,1,1,NULL,NULL);
INSERT INTO SUBCATEGORIA VALUES (NULL,(SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE_CATEGORIA='Gastos'),'Restaurantes','Comidas fuera',TRUE,FALSE,1,1,NULL,NULL);
INSERT INTO SUBCATEGORIA VALUES (NULL,(SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE_CATEGORIA='Gastos'),'Transporte','Movilidad',TRUE,FALSE,1,1,NULL,NULL);
INSERT INTO SUBCATEGORIA VALUES (NULL,(SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE_CATEGORIA='Gastos'),'Salud','Gastos médicos',TRUE,FALSE,1,1,NULL,NULL);
INSERT INTO SUBCATEGORIA VALUES (NULL,(SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE_CATEGORIA='Gastos'),'Entretenimiento','Ocio',TRUE,FALSE,1,1,NULL,NULL);
-- Ahorro
INSERT INTO SUBCATEGORIA VALUES (
  NULL,
  (SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE_CATEGORIA='Ahorro'),
  'Fondo Emergencia','Ahorro mensual',TRUE,TRUE,1,1,NULL,NULL
);

-- 4) PRESUPUESTO POR USUARIO (ENE-FEB 2025)
INSERT INTO PRESUPUESTO (
  ID_PRESUPUESTO, ID_USUARIO, NOMBRE_PRESUPUESTO,
  ANIO_INICIO, MES_INICIO, ANIO_FIN, MES_FIN,
  TOTAL_INGRESOS_PLANIFICADOS, TOTAL_GASTOS_PLANIFICADOS, TOTAL_AHORRO_PLANIFICADO,
  CREADO_EN, ESTADO_PRESUPUESTO, CREADO_POR, MODIFICADO_POR, MODIFICADO_EN
)
SELECT
  NULL,
  U.ID_USUARIO,
  'Presupuesto Ene-Feb 2025',
  2025,1, 2025,2,
  U.SALARIO_MENSUAL,
  U.SALARIO_MENSUAL * 0.75,
  U.SALARIO_MENSUAL * 0.15,
  NULL, 'activo', 1, 1, NULL
FROM USUARIO U;

-- 5) PRESUPUESTO_DETALLE (1 por subcategoría  por presupuesto)
INSERT INTO PRESUPUESTO_DETALLE (
  ID_DETALLE, ID_PRESUPUESTO, ID_SUBCATEGORIA,
  MONTO_MENSUAL_ASIGNADO, OBSERVACIONES,
  CREADO_POR, MODIFICADO_POR, CREADO_EN, MODIFICADO_EN
)
SELECT
  NULL,
  P.ID_PRESUPUESTO,
  S.ID_SUBCATEGORIA,
  CASE
    WHEN S.NOMBRE_SUBCATEGORIA='Salario Base'      THEN U.SALARIO_MENSUAL
    WHEN S.NOMBRE_SUBCATEGORIA='Alquiler'          THEN U.SALARIO_MENSUAL * 0.25
    WHEN S.NOMBRE_SUBCATEGORIA='Supermercado'      THEN U.SALARIO_MENSUAL * 0.15
    WHEN S.NOMBRE_SUBCATEGORIA='Restaurantes'      THEN U.SALARIO_MENSUAL * 0.08
    WHEN S.NOMBRE_SUBCATEGORIA='Transporte'        THEN U.SALARIO_MENSUAL * 0.07
    WHEN S.NOMBRE_SUBCATEGORIA='Fondo Emergencia'  THEN U.SALARIO_MENSUAL * 0.15
    ELSE U.SALARIO_MENSUAL * 0.05
  END,
  'Asignación automática',
  1,1,NULL,NULL
FROM PRESUPUESTO P
INNER JOIN USUARIO U ON U.ID_USUARIO = P.ID_USUARIO
INNER JOIN SUBCATEGORIA S ON S.ACTIVA = TRUE
WHERE S.NOMBRE_SUBCATEGORIA IN (
  'Salario Base','Alquiler','Energía Eléctrica','Internet','Supermercado',
  'Restaurantes','Transporte','Salud','Entretenimiento','Fondo Emergencia'
);


-- 6) OBLIGACIONES FIJAS (globales por subcategoría)
INSERT INTO OBLIGACION_FIJA (
  ID_OBLIGACION,
  ID_SUBCATEGORIA,
  NOMBRE_OBLIGACION,
  DESCRIPCION_OBLIGACION,
  MONTO_FIJO_MENSUAL,
  DIA_VENCIMIENTO,
  VIGENTE,
  FECHA_INICIO,
  FECHA_FIN,
  CREADO_POR,
  MODIFICADO_POR,
  CREADO_EN,
  MODIFICADO_EN
)
VALUES (
  NULL,
  (SELECT ID_SUBCATEGORIA 
   FROM SUBCATEGORIA 
   WHERE NOMBRE_SUBCATEGORIA = 'Internet'),
  'Servicio de Internet',
  'Pago mensual de servicio de internet',
  850.00,
  20,
  TRUE,
  DATE '2025-01-01',
  NULL,
  1,
  1,
  NULL,
  NULL
);


-- 7) TRANSACCIONES  (ENE y FEB 2025)
INSERT INTO TRANSACCION (
  ID_TRANSACCION, ID_DETALLE, ANIO_TRANSACCION, MES_TRANSACCION,
  ID_OBLIGACION, TIPO_TRANSACCION, DESCRIPCION, MONTO, FECHA_TRANSACCION,
  METODO_PAGO, NUMERO_FACTURA, OBSERVACIONES, REGISTRADO_EN,
  CREADO_POR, MODIFICADO_POR, CREADO_EN, MODIFICADO_EN
)
SELECT
  NULL, D.ID_DETALLE, 2025, 1,
  NULL, 'ingreso', 'Salario Enero',
  U.SALARIO_MENSUAL,
  DATE '2025-01-01',
  'transferencia', NULL, NULL, NULL,
  1,1,NULL,NULL
FROM PRESUPUESTO_DETALLE D
INNER JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO = D.ID_PRESUPUESTO
INNER JOIN USUARIO U ON U.ID_USUARIO = P.ID_USUARIO
INNER JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
WHERE S.NOMBRE_SUBCATEGORIA='Salario Base';

INSERT INTO TRANSACCION
SELECT
  NULL, D.ID_DETALLE, 2025, 2,
  NULL, 'ingreso', 'Salario Febrero',
  U.SALARIO_MENSUAL,
  DATE '2025-02-01',
  'transferencia', NULL, NULL, NULL,
  1,1,NULL,NULL
FROM PRESUPUESTO_DETALLE D
INNER JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO = D.ID_PRESUPUESTO
INNER JOIN USUARIO U ON U.ID_USUARIO = P.ID_USUARIO
INNER JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
WHERE S.NOMBRE_SUBCATEGORIA='Salario Base';

-- ALQUILER
INSERT INTO OBLIGACION_FIJA (
  ID_OBLIGACION, ID_SUBCATEGORIA,
  NOMBRE_OBLIGACION, DESCRIPCION_OBLIGACION,
  MONTO_FIJO_MENSUAL, DIA_VENCIMIENTO,
  VIGENTE, FECHA_INICIO, FECHA_FIN,
  CREADO_POR, MODIFICADO_POR, CREADO_EN, MODIFICADO_EN
)
VALUES (
  NULL,
  (SELECT ID_SUBCATEGORIA FROM SUBCATEGORIA WHERE NOMBRE_SUBCATEGORIA = 'Alquiler'),
  'Alquiler Mensual',
  'Pago recurrente de vivienda',
  6000.00,
  5,
  TRUE,
  DATE '2025-01-01',
  NULL,
  1, 1, NULL, NULL
);


-- ALQUILER ENERO
INSERT INTO TRANSACCION
SELECT
  NULL,
  D.ID_DETALLE,
  2025, 1,
  O.ID_OBLIGACION,
  'gasto',
  'Pago alquiler (Enero)',
  (U.SALARIO_MENSUAL * 0.25) + 150,
  DATE '2025-01-05',
  'transferencia',
  NULL,
  'Pago puntual',
  NULL,
  1,1,NULL,NULL
FROM PRESUPUESTO_DETALLE D
INNER JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO = D.ID_PRESUPUESTO
INNER JOIN USUARIO U ON U.ID_USUARIO = P.ID_USUARIO
INNER JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
INNER JOIN OBLIGACION_FIJA O
 ON O.NOMBRE_OBLIGACION = 'Alquiler Mensual'
WHERE S.NOMBRE_SUBCATEGORIA='Alquiler';

-- ALQUILER FEBRERO
INSERT INTO TRANSACCION
SELECT
  NULL,
  D.ID_DETALLE,
  2025, 2,
  O.ID_OBLIGACION,
  'gasto',
  'Pago alquiler (Febrero)',
  (U.SALARIO_MENSUAL * 0.25) - 50,
  DATE '2025-02-04',
  'transferencia',
  NULL,
  'Pago un día antes',
  NULL,
  1,1,NULL,NULL
FROM PRESUPUESTO_DETALLE D
INNER JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO = D.ID_PRESUPUESTO
INNER JOIN USUARIO U ON U.ID_USUARIO = P.ID_USUARIO
INNER JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
INNER JOIN OBLIGACION_FIJA O
 ON O.NOMBRE_OBLIGACION = 'Alquiler Mensual'
WHERE S.NOMBRE_SUBCATEGORIA='Alquiler';


INSERT INTO OBLIGACION_FIJA (
  ID_OBLIGACION, ID_SUBCATEGORIA,
  NOMBRE_OBLIGACION, DESCRIPCION_OBLIGACION,
  MONTO_FIJO_MENSUAL, DIA_VENCIMIENTO,
  VIGENTE, FECHA_INICIO, FECHA_FIN,
  CREADO_POR, MODIFICADO_POR, CREADO_EN, MODIFICADO_EN
)
VALUES (
  NULL,
  (SELECT ID_SUBCATEGORIA
   FROM SUBCATEGORIA
   WHERE NOMBRE_SUBCATEGORIA = 'Energía Eléctrica'),
  'Recibo de Luz',
  'Pago mensual de energía eléctrica',
  1200.00,
  15,
  TRUE,
  DATE '2025-01-01',
  NULL,
  1, 1, NULL, NULL
);

-- LUZ ENERO
INSERT INTO TRANSACCION
SELECT
  NULL, D.ID_DETALLE, 2025, 1,
  O.ID_OBLIGACION,
  'gasto', 'Pago recibo de luz (Enero)',
  (U.SALARIO_MENSUAL * 0.05) + 90,
  DATE '2025-01-15',
  'efectivo', NULL, NULL, NULL,
  1,1,NULL,NULL
FROM PRESUPUESTO_DETALLE D
INNER JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO = D.ID_PRESUPUESTO
INNER JOIN USUARIO U ON U.ID_USUARIO = P.ID_USUARIO
INNER JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
INNER JOIN OBLIGACION_FIJA O
 ON O.NOMBRE_OBLIGACION = 'Recibo de Luz'
WHERE S.NOMBRE_SUBCATEGORIA='Energía Eléctrica';

-- LUZ FEBRERO
INSERT INTO TRANSACCION
SELECT
  NULL, D.ID_DETALLE, 2025, 2,
  O.ID_OBLIGACION,
  'gasto', 'Pago recibo de luz (Febrero)',
  (U.SALARIO_MENSUAL * 0.05) - 40,
  DATE '2025-02-16',
  'efectivo', NULL, 'Pagado tarde 1 día', NULL,
  1,1,NULL,NULL
FROM PRESUPUESTO_DETALLE D
INNER JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO = D.ID_PRESUPUESTO
INNER JOIN USUARIO U ON U.ID_USUARIO = P.ID_USUARIO
INNER JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
INNER JOIN OBLIGACION_FIJA O
 ON O.NOMBRE_OBLIGACION = 'Recibo de Luz'
WHERE S.NOMBRE_SUBCATEGORIA='Energía Eléctrica';

-- INTERNET ENERO 
INSERT INTO TRANSACCION
SELECT
  NULL, D.ID_DETALLE, 2025, 1,
  O.ID_OBLIGACION,
  'gasto', 'Pago internet (Enero)',
  (U.SALARIO_MENSUAL * 0.05) + 30,
  DATE '2025-01-20',
  'tarjeta_debito', NULL, NULL, NULL,
  1,1,NULL,NULL
FROM PRESUPUESTO_DETALLE D
INNER JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO = D.ID_PRESUPUESTO
INNER JOIN USUARIO U ON U.ID_USUARIO = P.ID_USUARIO
INNER JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
INNER JOIN OBLIGACION_FIJA O ON O.NOMBRE_OBLIGACION = 'Servicio de Internet'
WHERE S.NOMBRE_SUBCATEGORIA='Internet';

-- INTERNET FEBRERO
INSERT INTO TRANSACCION
SELECT
  NULL, D.ID_DETALLE, 2025, 2,
  O.ID_OBLIGACION,
  'gasto', 'Pago internet (Febrero)',
  (U.SALARIO_MENSUAL * 0.05) + 10,
  DATE '2025-02-21',
  'tarjeta_debito', NULL, NULL, NULL,
  1,1,NULL,NULL
FROM PRESUPUESTO_DETALLE D
INNER JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO = D.ID_PRESUPUESTO
INNER JOIN USUARIO U ON U.ID_USUARIO = P.ID_USUARIO
INNER JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
INNER JOIN OBLIGACION_FIJA O ON O.NOMBRE_OBLIGACION = 'Servicio de Internet'
WHERE S.NOMBRE_SUBCATEGORIA='Internet';


-- GASTOS VARIABLES (varios movimientos repartidos) 
INSERT INTO TRANSACCION
SELECT NULL, D.ID_DETALLE, 2025, 1, NULL, 'gasto', 'Supermercado - compra 1', (U.SALARIO_MENSUAL*0.15)*0.22, DATE '2025-01-06', 'efectivo', NULL, NULL, NULL, 1,1,NULL,NULL
FROM PRESUPUESTO_DETALLE D JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO=D.ID_PRESUPUESTO
INNER JOIN USUARIO U ON U.ID_USUARIO=P.ID_USUARIO JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA=D.ID_SUBCATEGORIA
WHERE S.NOMBRE_SUBCATEGORIA='Supermercado';

INSERT INTO TRANSACCION
SELECT NULL, D.ID_DETALLE, 2025, 1, NULL, 'gasto', 'Supermercado - compra 2', (U.SALARIO_MENSUAL*0.15)*0.28, DATE '2025-01-13', 'tarjeta_debito', NULL, NULL, NULL, 1,1,NULL,NULL
FROM PRESUPUESTO_DETALLE D JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO=D.ID_PRESUPUESTO
INNER JOIN USUARIO U ON U.ID_USUARIO=P.ID_USUARIO JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA=D.ID_SUBCATEGORIA
WHERE S.NOMBRE_SUBCATEGORIA='Supermercado';

INSERT INTO TRANSACCION
SELECT NULL, D.ID_DETALLE, 2025, 1, NULL, 'gasto', 'Supermercado - compra 3', (U.SALARIO_MENSUAL*0.15)*0.18, DATE '2025-01-20', 'efectivo', NULL, NULL, NULL, 1,1,NULL,NULL
FROM PRESUPUESTO_DETALLE D JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO=D.ID_PRESUPUESTO
INNER JOIN USUARIO U ON U.ID_USUARIO=P.ID_USUARIO JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA=D.ID_SUBCATEGORIA
WHERE S.NOMBRE_SUBCATEGORIA='Supermercado';

INSERT INTO TRANSACCION
SELECT NULL, D.ID_DETALLE, 2025, 1, NULL, 'gasto', 'Supermercado - compra 4', 
(U.SALARIO_MENSUAL*0.15)*0.37, DATE '2025-01-28', 'tarjeta_debito', NULL, 'Incluye limpieza', NULL, 1,1,NULL,NULL
FROM PRESUPUESTO_DETALLE D JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO=D.ID_PRESUPUESTO
INNER JOIN USUARIO U ON U.ID_USUARIO=P.ID_USUARIO JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA=D.ID_SUBCATEGORIA
WHERE S.NOMBRE_SUBCATEGORIA='Supermercado';

-- FEB (variación)
INSERT INTO TRANSACCION
SELECT NULL, D.ID_DETALLE, 2025, 2, NULL, 'gasto', 'Supermercado - compra 1',
(U.SALARIO_MENSUAL*0.15)*0.25, DATE '2025-02-07', 'efectivo', NULL, NULL, NULL, 1,1,NULL,NULL
FROM PRESUPUESTO_DETALLE D JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO=D.ID_PRESUPUESTO
INNER JOIN USUARIO U ON U.ID_USUARIO=P.ID_USUARIO JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA=D.ID_SUBCATEGORIA
WHERE S.NOMBRE_SUBCATEGORIA='Supermercado';

INSERT INTO TRANSACCION
SELECT NULL, D.ID_DETALLE, 2025, 2, NULL, 'gasto', 'Supermercado - compra 2', (U.SALARIO_MENSUAL*0.15)*0.30, DATE '2025-02-14', 'tarjeta_debito', NULL, NULL, NULL, 1,1,NULL,NULL
FROM PRESUPUESTO_DETALLE D JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO=D.ID_PRESUPUESTO
INNER JOIN USUARIO U ON U.ID_USUARIO=P.ID_USUARIO JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA=D.ID_SUBCATEGORIA
WHERE S.NOMBRE_SUBCATEGORIA='Supermercado';

INSERT INTO TRANSACCION
SELECT NULL, D.ID_DETALLE, 2025, 2, NULL, 'gasto', 'Supermercado - compra 3', (U.SALARIO_MENSUAL*0.15)*0.16, DATE '2025-02-20', 'efectivo', NULL, NULL, NULL, 1,1,NULL,NULL
FROM PRESUPUESTO_DETALLE D JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO=D.ID_PRESUPUESTO
INNER JOIN USUARIO U ON U.ID_USUARIO=P.ID_USUARIO JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA=D.ID_SUBCATEGORIA
WHERE S.NOMBRE_SUBCATEGORIA='Supermercado';

INSERT INTO TRANSACCION
SELECT NULL, D.ID_DETALLE, 2025, 2, NULL, 'gasto', 'Supermercado - compra 4', (U.SALARIO_MENSUAL*0.15)*0.33, DATE '2025-02-27', 'tarjeta_debito', NULL, 'Compra grande', NULL, 1,1,NULL,NULL
FROM PRESUPUESTO_DETALLE D JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO=D.ID_PRESUPUESTO
INNER JOIN USUARIO U ON U.ID_USUARIO=P.ID_USUARIO JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA=D.ID_SUBCATEGORIA
WHERE S.NOMBRE_SUBCATEGORIA='Supermercado';


-- RESTAURANTES
-- Enero 2025 (3)
INSERT INTO TRANSACCION (
  ID_TRANSACCION, ID_DETALLE,
  ANIO_TRANSACCION, MES_TRANSACCION,
  ID_OBLIGACION, TIPO_TRANSACCION,
  DESCRIPCION, MONTO, FECHA_TRANSACCION,
  METODO_PAGO, NUMERO_FACTURA, OBSERVACIONES,
  REGISTRADO_EN, CREADO_POR, MODIFICADO_POR, CREADO_EN, MODIFICADO_EN
)
SELECT
  NULL, D.ID_DETALLE,
  2025, 1,
  NULL, 'gasto',
  'Restaurante - almuerzo', ROUND(U.SALARIO_MENSUAL * 0.018, 2), DATE '2025-01-07',
  'tarjeta_debito', NULL, 'Comida fuera',
  NULL, 1, 1, NULL, NULL
FROM PRESUPUESTO_DETALLE D
INNER JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO = D.ID_PRESUPUESTO
INNER JOIN USUARIO U ON U.ID_USUARIO = P.ID_USUARIO
INNER JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
WHERE P.ANIO_INICIO = 2025 AND P.MES_INICIO = 1 AND P.ANIO_FIN = 2025 AND P.MES_FIN = 2
  AND S.NOMBRE_SUBCATEGORIA = 'Restaurantes'

UNION ALL
SELECT
  NULL, D.ID_DETALLE,
  2025, 1,
  NULL, 'gasto',
  'Restaurante - cena', ROUND(U.SALARIO_MENSUAL * 0.022, 2), DATE '2025-01-16',
  'efectivo', NULL, 'Salida con amigos',
  NULL, 1, 1, NULL, NULL
FROM PRESUPUESTO_DETALLE D
INNER JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO = D.ID_PRESUPUESTO
INNER JOIN USUARIO U ON U.ID_USUARIO = P.ID_USUARIO
INNER JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
WHERE P.ANIO_INICIO = 2025 AND P.MES_INICIO = 1 AND P.ANIO_FIN = 2025 AND P.MES_FIN = 2
  AND S.NOMBRE_SUBCATEGORIA = 'Restaurantes'

UNION ALL
SELECT
  NULL, D.ID_DETALLE,
  2025, 1,
  NULL, 'gasto',
  'Cafeteria / snack', ROUND(U.SALARIO_MENSUAL * 0.012, 2), DATE '2025-01-25',
  'tarjeta_debito', NULL, 'Snack',
  NULL, 1, 1, NULL, NULL
FROM PRESUPUESTO_DETALLE D
INNER JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO = D.ID_PRESUPUESTO
INNER JOIN USUARIO U ON U.ID_USUARIO = P.ID_USUARIO
INNER JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
WHERE P.ANIO_INICIO = 2025 AND P.MES_INICIO = 1 AND P.ANIO_FIN = 2025 AND P.MES_FIN = 2
  AND S.NOMBRE_SUBCATEGORIA = 'Restaurantes';

-- Febrero 2025 (3) - con variación
INSERT INTO TRANSACCION (
  ID_TRANSACCION, ID_DETALLE,
  ANIO_TRANSACCION, MES_TRANSACCION,
  ID_OBLIGACION, TIPO_TRANSACCION,
  DESCRIPCION, MONTO, FECHA_TRANSACCION,
  METODO_PAGO, NUMERO_FACTURA, OBSERVACIONES,
  REGISTRADO_EN, CREADO_POR, MODIFICADO_POR, CREADO_EN, MODIFICADO_EN
)
SELECT
  NULL, D.ID_DETALLE,
  2025, 2,
  NULL, 'gasto',
  'Restaurante - almuerzo', ROUND(U.SALARIO_MENSUAL * 0.020, 2), DATE '2025-02-06',
  'tarjeta_debito', NULL, 'Comida fuera',
  NULL, 1, 1, NULL, NULL
FROM PRESUPUESTO_DETALLE D
INNER JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO = D.ID_PRESUPUESTO
INNER JOIN USUARIO U ON U.ID_USUARIO = P.ID_USUARIO
INNER JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
WHERE P.ANIO_INICIO = 2025 
  AND P.MES_INICIO = 1 
  AND P.ANIO_FIN = 2025 
  AND P.MES_FIN = 2
  AND S.NOMBRE_SUBCATEGORIA = 'Restaurantes'

UNION ALL
SELECT
  NULL, D.ID_DETALLE,
  2025, 2,
  NULL, 'gasto',
  'Restaurante - cena', ROUND(U.SALARIO_MENSUAL * 0.026, 2), DATE '2025-02-14',
  'tarjeta_credito', NULL, 'Cena especial',
  NULL, 1, 1, NULL, NULL
FROM PRESUPUESTO_DETALLE D
INNER JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO = D.ID_PRESUPUESTO
INNER JOIN USUARIO U ON U.ID_USUARIO = P.ID_USUARIO
INNER JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
WHERE P.ANIO_INICIO = 2025 
  AND P.MES_INICIO = 1 
  AND P.ANIO_FIN = 2025 
  AND P.MES_FIN = 2
  AND S.NOMBRE_SUBCATEGORIA = 'Restaurantes'

UNION ALL
SELECT
  NULL, D.ID_DETALLE,
  2025, 2,
  NULL, 'gasto',
  'Cafeteria / snack', ROUND(U.SALARIO_MENSUAL * 0.010, 2), DATE '2025-02-23',
  'efectivo', NULL, 'Snack',
  NULL, 1, 1, NULL, NULL
FROM PRESUPUESTO_DETALLE D
INNER JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO = D.ID_PRESUPUESTO
INNER JOIN USUARIO U ON U.ID_USUARIO = P.ID_USUARIO
INNER JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
WHERE P.ANIO_INICIO = 2025 
  AND P.MES_INICIO = 1 
  AND P.ANIO_FIN = 2025 
  AND P.MES_FIN = 2
  AND S.NOMBRE_SUBCATEGORIA = 'Restaurantes';


-- TRANSPORTE (6 por mes)
-- Enero 2025 (6)
INSERT INTO TRANSACCION (
  ID_TRANSACCION, ID_DETALLE,
  ANIO_TRANSACCION, MES_TRANSACCION,
  ID_OBLIGACION, TIPO_TRANSACCION,
  DESCRIPCION, MONTO, FECHA_TRANSACCION,
  METODO_PAGO, NUMERO_FACTURA, OBSERVACIONES,
  REGISTRADO_EN, CREADO_POR, MODIFICADO_POR, CREADO_EN, MODIFICADO_EN
)
SELECT NULL, D.ID_DETALLE, 2025, 1, NULL, 'gasto',
       'Transporte - uber/taxi', ROUND(U.SALARIO_MENSUAL * 0.006, 2), DATE '2025-01-03',
       'efectivo', NULL, 'Movilidad',
       NULL, 1, 1, NULL, NULL
FROM PRESUPUESTO_DETALLE D
INNER JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO = D.ID_PRESUPUESTO
INNER JOIN USUARIO U ON U.ID_USUARIO = P.ID_USUARIO
INNER JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
WHERE P.ANIO_INICIO=2025 AND P.MES_INICIO=1 AND P.ANIO_FIN=2025 AND P.MES_FIN=2
  AND S.NOMBRE_SUBCATEGORIA='Transporte'

UNION ALL
SELECT NULL, D.ID_DETALLE, 2025, 1, NULL, 'gasto',
       'Transporte - pasaje', ROUND(U.SALARIO_MENSUAL * 0.0035, 2), DATE '2025-01-08',
       'efectivo', NULL, 'Pasaje',
       NULL, 1, 1, NULL, NULL
FROM PRESUPUESTO_DETALLE D
INNER JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO = D.ID_PRESUPUESTO
INNER JOIN USUARIO U ON U.ID_USUARIO = P.ID_USUARIO
INNER JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
WHERE P.ANIO_INICIO=2025 AND P.MES_INICIO=1 AND P.ANIO_FIN=2025 AND P.MES_FIN=2
  AND S.NOMBRE_SUBCATEGORIA='Transporte'

UNION ALL
SELECT NULL, D.ID_DETALLE, 2025, 1, NULL, 'gasto',
       'Transporte - combustible', ROUND(U.SALARIO_MENSUAL * 0.009, 2), DATE '2025-01-12',
       'tarjeta_debito', NULL, 'Gasolina',
       NULL, 1, 1, NULL, NULL
FROM PRESUPUESTO_DETALLE D
INNER JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO = D.ID_PRESUPUESTO
INNER JOIN USUARIO U ON U.ID_USUARIO = P.ID_USUARIO
INNER JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
WHERE P.ANIO_INICIO=2025 AND P.MES_INICIO=1 AND P.ANIO_FIN=2025 AND P.MES_FIN=2
  AND S.NOMBRE_SUBCATEGORIA='Transporte'

UNION ALL
SELECT NULL, D.ID_DETALLE, 2025, 1, NULL, 'gasto',
       'Transporte - parqueo', ROUND(U.SALARIO_MENSUAL * 0.0025, 2), DATE '2025-01-18',
       'efectivo', NULL, 'Parqueo',
       NULL, 1, 1, NULL, NULL
FROM PRESUPUESTO_DETALLE D
INNER JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO = D.ID_PRESUPUESTO
INNER JOIN USUARIO U ON U.ID_USUARIO = P.ID_USUARIO
INNER JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
WHERE P.ANIO_INICIO=2025 AND P.MES_INICIO=1 AND P.ANIO_FIN=2025 AND P.MES_FIN=2
  AND S.NOMBRE_SUBCATEGORIA='Transporte'

UNION ALL
SELECT NULL, D.ID_DETALLE, 2025, 1, NULL, 'gasto',
       'Transporte - pasaje', ROUND(U.SALARIO_MENSUAL * 0.0030, 2), DATE '2025-01-22',
       'efectivo', NULL, 'Pasaje',
       NULL, 1, 1, NULL, NULL
FROM PRESUPUESTO_DETALLE D
INNER JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO = D.ID_PRESUPUESTO
INNER JOIN USUARIO U ON U.ID_USUARIO = P.ID_USUARIO
INNER JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
WHERE P.ANIO_INICIO=2025 AND P.MES_INICIO=1 AND P.ANIO_FIN=2025 AND P.MES_FIN=2
  AND S.NOMBRE_SUBCATEGORIA='Transporte'

UNION ALL
SELECT NULL, D.ID_DETALLE, 2025, 1, NULL, 'gasto',
       'Transporte - uber/taxi', ROUND(U.SALARIO_MENSUAL * 0.0065, 2), DATE '2025-01-29',
       'tarjeta_debito', NULL, 'Movilidad',
       NULL, 1, 1, NULL, NULL
FROM PRESUPUESTO_DETALLE D
INNER JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO = D.ID_PRESUPUESTO
INNER JOIN USUARIO U ON U.ID_USUARIO = P.ID_USUARIO
INNER JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
WHERE P.ANIO_INICIO=2025 AND P.MES_INICIO=1 AND P.ANIO_FIN=2025 AND P.MES_FIN=2
  AND S.NOMBRE_SUBCATEGORIA='Transporte';

-- TRANSPORTE FEBRERO 2025 (6)
INSERT INTO TRANSACCION (
  ID_TRANSACCION, ID_DETALLE,
  ANIO_TRANSACCION, MES_TRANSACCION,
  ID_OBLIGACION, TIPO_TRANSACCION,
  DESCRIPCION, MONTO, FECHA_TRANSACCION,
  METODO_PAGO, NUMERO_FACTURA, OBSERVACIONES,
  REGISTRADO_EN, CREADO_POR, MODIFICADO_POR, CREADO_EN, MODIFICADO_EN
)
SELECT NULL, D.ID_DETALLE, 2025, 2, NULL, 'gasto',
       'Transporte - uber/taxi', ROUND(U.SALARIO_MENSUAL * 0.0062, 2), DATE '2025-02-02',
       'efectivo', NULL, 'Movilidad',
       NULL, 1, 1, NULL, NULL
FROM PRESUPUESTO_DETALLE D
INNER JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO = D.ID_PRESUPUESTO
INNER JOIN USUARIO U ON U.ID_USUARIO = P.ID_USUARIO
INNER JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
WHERE P.ANIO_INICIO=2025 AND P.MES_INICIO=1 AND P.ANIO_FIN=2025 AND P.MES_FIN=2
  AND S.NOMBRE_SUBCATEGORIA='Transporte'

UNION ALL
SELECT NULL, D.ID_DETALLE, 2025, 2, NULL, 'gasto',
       'Transporte - pasaje', ROUND(U.SALARIO_MENSUAL * 0.0038, 2), DATE '2025-02-06',
       'efectivo', NULL, 'Pasaje',
       NULL, 1, 1, NULL, NULL
FROM PRESUPUESTO_DETALLE D
INNER JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO = D.ID_PRESUPUESTO
INNER JOIN USUARIO U ON U.ID_USUARIO = P.ID_USUARIO
INNER JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
WHERE P.ANIO_INICIO=2025 AND P.MES_INICIO=1 AND P.ANIO_FIN=2025 AND P.MES_FIN=2
  AND S.NOMBRE_SUBCATEGORIA='Transporte'

UNION ALL
SELECT NULL, D.ID_DETALLE, 2025, 2, NULL, 'gasto',
       'Transporte - combustible', ROUND(U.SALARIO_MENSUAL * 0.0086, 2), DATE '2025-02-11',
       'tarjeta_debito', NULL, 'Gasolina',
       NULL, 1, 1, NULL, NULL
FROM PRESUPUESTO_DETALLE D
INNER JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO = D.ID_PRESUPUESTO
INNER JOIN USUARIO U ON U.ID_USUARIO = P.ID_USUARIO
INNER JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
WHERE P.ANIO_INICIO=2025 AND P.MES_INICIO=1 AND P.ANIO_FIN=2025 AND P.MES_FIN=2
  AND S.NOMBRE_SUBCATEGORIA='Transporte'

UNION ALL
SELECT NULL, D.ID_DETALLE, 2025, 2, NULL, 'gasto',
       'Transporte - parqueo', ROUND(U.SALARIO_MENSUAL * 0.0023, 2), DATE '2025-02-16',
       'efectivo', NULL, 'Parqueo',
       NULL, 1, 1, NULL, NULL
FROM PRESUPUESTO_DETALLE D
INNER JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO = D.ID_PRESUPUESTO
INNER JOIN USUARIO U ON U.ID_USUARIO = P.ID_USUARIO
INNER JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
WHERE P.ANIO_INICIO=2025 AND P.MES_INICIO=1 AND P.ANIO_FIN=2025 AND P.MES_FIN=2
  AND S.NOMBRE_SUBCATEGORIA='Transporte'

UNION ALL
SELECT NULL, D.ID_DETALLE, 2025, 2, NULL, 'gasto',
       'Transporte - pasaje', ROUND(U.SALARIO_MENSUAL * 0.0032, 2), DATE '2025-02-20',
       'efectivo', NULL, 'Pasaje',
       NULL, 1, 1, NULL, NULL
FROM PRESUPUESTO_DETALLE D
INNER JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO = D.ID_PRESUPUESTO
INNER JOIN USUARIO U ON U.ID_USUARIO = P.ID_USUARIO
INNER JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
WHERE P.ANIO_INICIO=2025 AND P.MES_INICIO=1 AND P.ANIO_FIN=2025 AND P.MES_FIN=2
  AND S.NOMBRE_SUBCATEGORIA='Transporte'

UNION ALL
SELECT NULL, D.ID_DETALLE, 2025, 2, NULL, 'gasto',
       'Transporte - uber/taxi', ROUND(U.SALARIO_MENSUAL * 0.0067, 2), DATE '2025-02-26',
       'tarjeta_debito', NULL, 'Movilidad',
       NULL, 1, 1, NULL, NULL
FROM PRESUPUESTO_DETALLE D
INNER JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO = D.ID_PRESUPUESTO
INNER JOIN USUARIO U ON U.ID_USUARIO = P.ID_USUARIO
INNER JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
WHERE P.ANIO_INICIO=2025 AND P.MES_INICIO=1 AND P.ANIO_FIN=2025 AND P.MES_FIN=2
  AND S.NOMBRE_SUBCATEGORIA='Transporte';

-- ENTRETENIMIENTO
-- ENTRETENIMIENTO ENERO 
INSERT INTO TRANSACCION (
  ID_TRANSACCION, ID_DETALLE,
  ANIO_TRANSACCION, MES_TRANSACCION,
  ID_OBLIGACION, TIPO_TRANSACCION,
  DESCRIPCION, MONTO, FECHA_TRANSACCION,
  METODO_PAGO, NUMERO_FACTURA, OBSERVACIONES,
  REGISTRADO_EN, CREADO_POR, MODIFICADO_POR, CREADO_EN, MODIFICADO_EN
)
SELECT NULL, D.ID_DETALLE, 2025, 1, NULL, 'gasto',
       'Entretenimiento - cine', ROUND(U.SALARIO_MENSUAL * 0.010, 2), DATE '2025-01-10',
       'tarjeta_debito', NULL, 'Ocio',
       NULL, 1, 1, NULL, NULL
FROM PRESUPUESTO_DETALLE D
INNER JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO = D.ID_PRESUPUESTO
INNER JOIN USUARIO U ON U.ID_USUARIO = P.ID_USUARIO
INNER JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
WHERE P.ANIO_INICIO=2025 AND P.MES_INICIO=1 AND P.ANIO_FIN=2025 AND P.MES_FIN=2
  AND S.NOMBRE_SUBCATEGORIA='Entretenimiento'

UNION ALL
SELECT NULL, D.ID_DETALLE, 2025, 1, NULL, 'gasto',
       'Entretenimiento - streaming', ROUND(U.SALARIO_MENSUAL * 0.006, 2), DATE '2025-01-21',
       'transferencia', NULL, 'Suscripción',
       NULL, 1, 1, NULL, NULL
FROM PRESUPUESTO_DETALLE D
INNER JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO = D.ID_PRESUPUESTO
INNER JOIN USUARIO U ON U.ID_USUARIO = P.ID_USUARIO
INNER JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
WHERE P.ANIO_INICIO=2025 AND P.MES_INICIO=1 AND P.ANIO_FIN=2025 AND P.MES_FIN=2
  AND S.NOMBRE_SUBCATEGORIA='Entretenimiento';

-- ENTRETENIMIENTO FEBRERO
INSERT INTO TRANSACCION (
  ID_TRANSACCION, ID_DETALLE,
  ANIO_TRANSACCION, MES_TRANSACCION,
  ID_OBLIGACION, TIPO_TRANSACCION,
  DESCRIPCION, MONTO, FECHA_TRANSACCION,
  METODO_PAGO, NUMERO_FACTURA, OBSERVACIONES,
  REGISTRADO_EN, CREADO_POR, MODIFICADO_POR, CREADO_EN, MODIFICADO_EN
)
SELECT NULL, D.ID_DETALLE, 2025, 2, NULL, 'gasto',
       'Entretenimiento - eventos', ROUND(U.SALARIO_MENSUAL * 0.012, 2), DATE '2025-02-09',
       'efectivo', NULL, 'Ocio',
       NULL, 1, 1, NULL, NULL
FROM PRESUPUESTO_DETALLE D
INNER JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO = D.ID_PRESUPUESTO
INNER JOIN USUARIO U ON U.ID_USUARIO = P.ID_USUARIO
INNER JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
WHERE P.ANIO_INICIO=2025 AND P.MES_INICIO=1 AND P.ANIO_FIN=2025 AND P.MES_FIN=2
  AND S.NOMBRE_SUBCATEGORIA='Entretenimiento'

UNION ALL
SELECT NULL, D.ID_DETALLE, 2025, 2, NULL, 'gasto',
       'Entretenimiento - streaming', ROUND(U.SALARIO_MENSUAL * 0.006, 2), DATE '2025-02-22',
       'transferencia', NULL, 'Suscripción',
       NULL, 1, 1, NULL, NULL
FROM PRESUPUESTO_DETALLE D
INNER JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO = D.ID_PRESUPUESTO
INNER JOIN USUARIO U ON U.ID_USUARIO = P.ID_USUARIO
INNER JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
WHERE P.ANIO_INICIO=2025 AND P.MES_INICIO=1 AND P.ANIO_FIN=2025 AND P.MES_FIN=2
  AND S.NOMBRE_SUBCATEGORIA='Entretenimiento';

-- SALUD 
-- Enero 
INSERT INTO TRANSACCION (
  ID_TRANSACCION, ID_DETALLE,
  ANIO_TRANSACCION, MES_TRANSACCION,
  ID_OBLIGACION, TIPO_TRANSACCION,
  DESCRIPCION, MONTO, FECHA_TRANSACCION,
  METODO_PAGO, NUMERO_FACTURA, OBSERVACIONES,
  REGISTRADO_EN, CREADO_POR, MODIFICADO_POR, CREADO_EN, MODIFICADO_EN
)
SELECT NULL, D.ID_DETALLE, 2025, 1, NULL, 'gasto',
       'Salud - farmacia', ROUND(U.SALARIO_MENSUAL * 0.007, 2), DATE '2025-01-14',
       'efectivo', NULL, 'Compra médica',
       NULL, 1, 1, NULL, NULL
FROM PRESUPUESTO_DETALLE D
INNER JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO = D.ID_PRESUPUESTO
INNER JOIN USUARIO U ON U.ID_USUARIO = P.ID_USUARIO
INNER JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
WHERE P.ANIO_INICIO=2025 AND P.MES_INICIO=1 AND P.ANIO_FIN=2025 AND P.MES_FIN=2
  AND S.NOMBRE_SUBCATEGORIA='Salud';

-- Febrero 
INSERT INTO TRANSACCION (
  ID_TRANSACCION, ID_DETALLE,
  ANIO_TRANSACCION, MES_TRANSACCION,
  ID_OBLIGACION, TIPO_TRANSACCION,
  DESCRIPCION, MONTO, FECHA_TRANSACCION,
  METODO_PAGO, NUMERO_FACTURA, OBSERVACIONES,
  REGISTRADO_EN, CREADO_POR, MODIFICADO_POR, CREADO_EN, MODIFICADO_EN
)
SELECT NULL, D.ID_DETALLE, 2025, 2, NULL, 'gasto',
       'Salud - consulta', ROUND(U.SALARIO_MENSUAL * 0.010, 2), DATE '2025-02-18',
       'tarjeta_debito', NULL, 'Consulta',
       NULL, 1, 1, NULL, NULL
FROM PRESUPUESTO_DETALLE D
INNER JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO = D.ID_PRESUPUESTO
INNER JOIN USUARIO U ON U.ID_USUARIO = P.ID_USUARIO
INNER JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
WHERE P.ANIO_INICIO=2025 AND P.MES_INICIO=1 AND P.ANIO_FIN=2025 AND P.MES_FIN=2
  AND S.NOMBRE_SUBCATEGORIA='Salud';


-- FONDO EMERGENCIA 
-- Enero 
INSERT INTO TRANSACCION (
  ID_TRANSACCION, ID_DETALLE,
  ANIO_TRANSACCION, MES_TRANSACCION,
  ID_OBLIGACION, TIPO_TRANSACCION,
  DESCRIPCION, MONTO, FECHA_TRANSACCION,
  METODO_PAGO, NUMERO_FACTURA, OBSERVACIONES,
  REGISTRADO_EN, CREADO_POR, MODIFICADO_POR, CREADO_EN, MODIFICADO_EN
)
SELECT
  NULL, D.ID_DETALLE,
  2025, 1,
  NULL, 'ahorro',
  'Ahorro - fondo emergencia', ROUND(U.SALARIO_MENSUAL * 0.135, 2), DATE '2025-01-27',
  'transferencia', NULL, 'Aporte ahorro',
  NULL, 1, 1, NULL, NULL
FROM PRESUPUESTO_DETALLE D
INNER JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO = D.ID_PRESUPUESTO
INNER JOIN USUARIO U ON U.ID_USUARIO = P.ID_USUARIO
INNER JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
WHERE P.ANIO_INICIO=2025 AND P.MES_INICIO=1 AND P.ANIO_FIN=2025 AND P.MES_FIN=2
  AND S.NOMBRE_SUBCATEGORIA='Fondo Emergencia';

-- Febrero 
INSERT INTO TRANSACCION (
  ID_TRANSACCION, ID_DETALLE,
  ANIO_TRANSACCION, MES_TRANSACCION,
  ID_OBLIGACION, TIPO_TRANSACCION,
  DESCRIPCION, MONTO, FECHA_TRANSACCION,
  METODO_PAGO, NUMERO_FACTURA, OBSERVACIONES,
  REGISTRADO_EN, CREADO_POR, MODIFICADO_POR, CREADO_EN, MODIFICADO_EN
)
SELECT
  NULL, D.ID_DETALLE,
  2025, 2,
  NULL, 'ahorro',
  'Ahorro - fondo emergencia', ROUND(U.SALARIO_MENSUAL * 0.145, 2), DATE '2025-02-25',
  'transferencia', NULL, 'Aporte ahorro',
  NULL, 1, 1, NULL, NULL
FROM PRESUPUESTO_DETALLE D
INNER JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO = D.ID_PRESUPUESTO
INNER JOIN USUARIO U ON U.ID_USUARIO = P.ID_USUARIO
INNER JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
WHERE P.ANIO_INICIO=2025 AND P.MES_INICIO=1 AND P.ANIO_FIN=2025 AND P.MES_FIN=2
  AND S.NOMBRE_SUBCATEGORIA='Fondo Emergencia';
