CREATE TABLE USUARIO (
    ID_USUARIO INTEGER PRIMARY KEY,
    PRIMER_NOMBRE VARCHAR(80),
    SEGUNDO_NOMBRE VARCHAR(80),
    PRIMER_APELLIDO VARCHAR(80),
    SEGUNDO_APELLIDO VARCHAR(80),
    CORREO_ELECTRONICO VARCHAR(120),
    CLAVE VARCHAR(255),
    SALARIO_MENSUAL DECIMAL(18,2),
    ESTADO_ACTIVO BOOLEAN,
    CREADO_POR INTEGER,
    MODIFICADO_POR INTEGER,
    CREADO_EN TIMESTAMP,
    MODIFICADO_EN TIMESTAMP
);

CREATE TABLE CATEGORIA (
    ID_CATEGORIA INTEGER PRIMARY KEY,
    NOMBRE_CATEGORIA VARCHAR(60),
    DESCRIPCION_CATEGORIA VARCHAR(150),
    TIPO_CATEGORIA VARCHAR(20),
    CREADO_POR INTEGER,
    MODIFICADO_POR INTEGER,
    CREADO_EN TIMESTAMP,
    MODIFICADO_EN TIMESTAMP
);

CREATE TABLE SUBCATEGORIA (
    ID_SUBCATEGORIA INTEGER PRIMARY KEY,
    ID_CATEGORIA INTEGER,
    NOMBRE_SUBCATEGORIA VARCHAR(60),
    DESCRIPCION_SUBCATEGORIA VARCHAR(150),
    ACTIVA BOOLEAN,
    ES_POR_DEFECTO BOOLEAN,
    CREADO_POR INTEGER,
    MODIFICADO_POR INTEGER,
    CREADO_EN TIMESTAMP,
    MODIFICADO_EN TIMESTAMP
);

CREATE TABLE PRESUPUESTO (
    ID_PRESUPUESTO INTEGER PRIMARY KEY,
    ID_USUARIO INTEGER,
    NOMBRE_PRESUPUESTO VARCHAR(120),
    ANIO_INICIO INTEGER,
    MES_INICIO INTEGER,
    ANIO_FIN INTEGER,
    MES_FIN INTEGER,
    TOTAL_INGRESOS_PLANIFICADOS DECIMAL(18,2),
    TOTAL_GASTOS_PLANIFICADOS DECIMAL(18,2),
    TOTAL_AHORRO_PLANIFICADO DECIMAL(18,2),
    CREADO_EN TIMESTAMP,
    ESTADO_PRESUPUESTO VARCHAR(20),
    CREADO_POR INTEGER,
    MODIFICADO_POR INTEGER,
    MODIFICADO_EN TIMESTAMP
);

CREATE TABLE PRESUPUESTO_DETALLE (
    ID_DETALLE INTEGER PRIMARY KEY,
    ID_PRESUPUESTO INTEGER,
    ID_SUBCATEGORIA INTEGER,
    MONTO_MENSUAL_ASIGNADO DECIMAL(18,2),
    OBSERVACIONES VARCHAR(200),
    CREADO_POR INTEGER,
    MODIFICADO_POR INTEGER,
    CREADO_EN TIMESTAMP,
    MODIFICADO_EN TIMESTAMP
);

CREATE TABLE OBLIGACION_FIJA (
    ID_OBLIGACION INTEGER PRIMARY KEY,
    ID_SUBCATEGORIA INTEGER,
    NOMBRE_OBLIGACION VARCHAR(100),
    DESCRIPCION_OBLIGACION VARCHAR(200),
    MONTO_FIJO_MENSUAL DECIMAL(18,2),
    DIA_VENCIMIENTO INTEGER,
    VIGENTE BOOLEAN,
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    CREADO_POR INTEGER,
    MODIFICADO_POR INTEGER,
    CREADO_EN TIMESTAMP,
    MODIFICADO_EN TIMESTAMP
);

CREATE TABLE TRANSACCION (
    ID_TRANSACCION INTEGER PRIMARY KEY,
    ID_DETALLE INTEGER,
    ANIO_TRANSACCION INTEGER,
    MES_TRANSACCION INTEGER,
    ID_OBLIGACION INTEGER,
    TIPO_TRANSACCION VARCHAR(20),
    DESCRIPCION VARCHAR(200),
    MONTO DECIMAL(18,2),
    FECHA_TRANSACCION DATE,
    METODO_PAGO VARCHAR(30),
    NUMERO_FACTURA VARCHAR(40),
    OBSERVACIONES VARCHAR(200),
    REGISTRADO_EN TIMESTAMP,
    CREADO_POR INTEGER,
    MODIFICADO_POR INTEGER,
    CREADO_EN TIMESTAMP,
    MODIFICADO_EN TIMESTAMP
);

CREATE TABLE OBLIGACIONFIJA_TRANSACCION (
    ID_OBLIGACION INTEGER,
    ID_TRANSACCION INTEGER,
    CREADO_POR INTEGER,
    MODIFICADO_POR INTEGER,
    CREADO_EN TIMESTAMP,
    MODIFICADO_EN TIMESTAMP
);