-- usuario a presupuesto 
ALTER TABLE PRESUPUESTO 
ADD CONSTRAINT FK_PRESUPUESTO_USUARIO
FOREIGN KEY (ID_USUARIO)
REFERENCES USUARIO (ID_USUARIO)

--presupuesto a presupuesto_detalle
ALTER TABLE PRESUPUESTO_DETALLE 
ADD CONSTRAINT FK_PRESDET_PRESUPUESTO
FOREIGN KEY (ID_PRESUPUESTO)
REFERENCES PRESUPUESTO (ID_PRESUPUESTO);

--categoria a subcategoria
ALTER TABLE SUBCATEGORIA
ADD CONSTRAINT FK_SUBCATEGORIA_CATEGORIA
FOREIGN KEY (ID_CATEGORIA)
REFERENCES CATEGORIA (ID_CATEGORIA);

--subcategoria a presupuesto_detalle
ALTER TABLE PRESUPUESTO_DETALLE
ADD CONSTRAINT FK_PRESDET_SUBCATEGORIA
FOREIGN KEY (ID_SUBCATEGORIA)
REFERENCES SUBCATEGORIA (ID_SUBCATEGORIA);

--subcategoria a obligacion_fija
ALTER TABLE OBLIGACION_FIJA
ADD CONSTRAINT FK_OBLIGACION_SUBCATEGORIA
FOREIGN KEY (ID_SUBCATEGORIA)
REFERENCES SUBCATEGORIA (ID_SUBCATEGORIA);

--presupuesto_detalle a transaccion
ALTER TABLE TRANSACCION
ADD CONSTRAINT FK_TRANSACCION_DETALLE
FOREIGN KEY (ID_DETALLE)
REFERENCES PRESUPUESTO_DETALLE (ID_DETALLE);

--obligacion_fija a transaccion
ALTER TABLE TRANSACCION
ADD CONSTRAINT FK_TRANSACCION_OBLIGACION
FOREIGN KEY (ID_OBLIGACION)
REFERENCES OBLIGACION_FIJA (ID_OBLIGACION);

--obligacion_fija a obligacionfija_transaccion
ALTER TABLE OBLIGACIONFIJA_TRANSACCION
ADD CONSTRAINT FK_OFT_OBLIGACION
FOREIGN KEY (ID_OBLIGACION)
REFERENCES OBLIGACION_FIJA (ID_OBLIGACION);

--transaccion a obligacionfija_trasnaccion
ALTER TABLE OBLIGACIONFIJA_TRANSACCION
ADD CONSTRAINT FK_OFT_TRANSACCION
FOREIGN KEY (ID_TRANSACCION)
REFERENCES TRANSACCION (ID_TRANSACCION);

