SET TERM ^ ;

-- 1) fn_monto_ejec(id_subcategoria, anio, mes)
CREATE OR ALTER FUNCTION FN_MONTO_EJEC(
    P_ID_SUBCATEGORIA INTEGER,
    P_ANIO INTEGER,
    P_MES INTEGER
)
RETURNS DECIMAL(18,2)
AS
DECLARE VARIABLE V_TOTAL DECIMAL(18,2);
BEGIN
  V_TOTAL = 0;

  SELECT COALESCE(SUM(T.MONTO), 0)
  FROM TRANSACCION T
  INNER JOIN PRESUPUESTO_DETALLE D ON D.ID_DETALLE = T.ID_DETALLE
  WHERE D.ID_SUBCATEGORIA = :P_ID_SUBCATEGORIA
    AND T.ANIO_TRANSACCION = :P_ANIO
    AND T.MES_TRANSACCION  = :P_MES
  INTO :V_TOTAL;

  RETURN V_TOTAL;
END^

-- 2) fn_porc_ejec(id_subcategoria, id_presupuesto, anio, mes)

CREATE OR ALTER FUNCTION FN_PORC_EJEC(
    P_ID_SUBCATEGORIA INTEGER,
    P_ID_PRESUPUESTO INTEGER,
    P_ANIO INTEGER,
    P_MES INTEGER
)
RETURNS DECIMAL(9,2)
AS
DECLARE VARIABLE V_EJEC DECIMAL(18,2);
DECLARE VARIABLE V_PRES DECIMAL(18,2);
DECLARE VARIABLE V_PORC DECIMAL(9,2);
BEGIN
  V_EJEC = 0;
  V_PRES = 0;
  V_PORC = 0;

  SELECT COALESCE(D.MONTO_MENSUAL_ASIGNADO, 0)
  FROM PRESUPUESTO_DETALLE D
  WHERE D.ID_PRESUPUESTO = :P_ID_PRESUPUESTO
    AND D.ID_SUBCATEGORIA = :P_ID_SUBCATEGORIA
  INTO :V_PRES;

  SELECT COALESCE(SUM(T.MONTO), 0)
  FROM TRANSACCION T
  INNER JOIN PRESUPUESTO_DETALLE D ON D.ID_DETALLE = T.ID_DETALLE
  WHERE D.ID_PRESUPUESTO = :P_ID_PRESUPUESTO
    AND D.ID_SUBCATEGORIA = :P_ID_SUBCATEGORIA
    AND T.ANIO_TRANSACCION = :P_ANIO
    AND T.MES_TRANSACCION  = :P_MES
  INTO :V_EJEC;

  IF (V_PRES IS NULL OR V_PRES = 0) THEN
    V_PORC = 0;
  ELSE
    V_PORC = (V_EJEC / V_PRES) * 100;

  RETURN V_PORC;
END^


-- 3) fn_bal_sub(id_presupuesto, id_subcategoria, anio, mes)
CREATE OR ALTER FUNCTION FN_BAL_SUB(
    P_ID_PRESUPUESTO INTEGER,
    P_ID_SUBCATEGORIA INTEGER,
    P_ANIO INTEGER,
    P_MES INTEGER
)
RETURNS DECIMAL(18,2)
AS
DECLARE VARIABLE V_EJEC DECIMAL(18,2);
DECLARE VARIABLE V_PRES DECIMAL(18,2);
BEGIN
  V_EJEC = 0;
  V_PRES = 0;

  SELECT COALESCE(D.MONTO_MENSUAL_ASIGNADO, 0)
  FROM PRESUPUESTO_DETALLE D
  WHERE D.ID_PRESUPUESTO = :P_ID_PRESUPUESTO
    AND D.ID_SUBCATEGORIA = :P_ID_SUBCATEGORIA
  INTO :V_PRES;

  SELECT COALESCE(SUM(T.MONTO), 0)
  FROM TRANSACCION T
  INNER JOIN PRESUPUESTO_DETALLE D ON D.ID_DETALLE = T.ID_DETALLE
  WHERE D.ID_PRESUPUESTO = :P_ID_PRESUPUESTO
    AND D.ID_SUBCATEGORIA = :P_ID_SUBCATEGORIA
    AND T.ANIO_TRANSACCION = :P_ANIO
    AND T.MES_TRANSACCION  = :P_MES
  INTO :V_EJEC;

  RETURN (V_PRES - V_EJEC);
END^


-- 4) fn_tot_cat_mes(id_categoria, id_presupuesto, anio, mes)
CREATE OR ALTER FUNCTION FN_TOT_CAT_MES(
    P_ID_CATEGORIA INTEGER,
    P_ID_PRESUPUESTO INTEGER,
    P_ANIO INTEGER,
    P_MES INTEGER
)
RETURNS DECIMAL(18,2)
AS
DECLARE VARIABLE V_TOTAL DECIMAL(18,2);
BEGIN
  V_TOTAL = 0;

  SELECT COALESCE(SUM(D.MONTO_MENSUAL_ASIGNADO), 0)
  FROM PRESUPUESTO_DETALLE D
  INNER JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
  WHERE D.ID_PRESUPUESTO = :P_ID_PRESUPUESTO
    AND S.ID_CATEGORIA = :P_ID_CATEGORIA
  INTO :V_TOTAL;

  RETURN V_TOTAL;
END^

-- 5) fn_tot_ejec_cat(id_categoria, anio, mes)
CREATE OR ALTER FUNCTION FN_TOT_EJEC_CAT(
    P_ID_CATEGORIA INTEGER,
    P_ANIO INTEGER,
    P_MES INTEGER
)
RETURNS DECIMAL(18,2)
AS
DECLARE VARIABLE V_TOTAL DECIMAL(18,2);
BEGIN
  V_TOTAL = 0;

  SELECT COALESCE(SUM(T.MONTO), 0)
  FROM TRANSACCION T
  INNER JOIN PRESUPUESTO_DETALLE D ON D.ID_DETALLE = T.ID_DETALLE
  INNER JOIN SUBCATEGORIA S ON S.ID_SUBCATEGORIA = D.ID_SUBCATEGORIA
  WHERE S.ID_CATEGORIA = :P_ID_CATEGORIA
    AND T.ANIO_TRANSACCION = :P_ANIO
    AND T.MES_TRANSACCION  = :P_MES
  INTO :V_TOTAL;

  RETURN V_TOTAL;
END^

-- 6) fn_dias_venc(id_obligacion)
CREATE OR ALTER FUNCTION FN_DIAS_VENC(
    P_ID_OBLIGACION INTEGER
)
RETURNS INTEGER
AS
DECLARE VARIABLE V_DIA INTEGER;
DECLARE VARIABLE V_VIG BOOLEAN;
DECLARE VARIABLE V_HOY DATE;
DECLARE VARIABLE V_FEC_VENC DATE;
DECLARE VARIABLE V_PRIM_MES DATE;
BEGIN
  V_HOY = CURRENT_DATE;

  SELECT O.DIA_VENCIMIENTO, O.VIGENTE
  FROM OBLIGACION_FIJA O
  WHERE O.ID_OBLIGACION = :P_ID_OBLIGACION
  INTO :V_DIA, :V_VIG;

  IF (V_DIA IS NULL) THEN RETURN NULL;
  IF (V_VIG IS NULL OR V_VIG = FALSE) THEN RETURN NULL;

  V_PRIM_MES = DATEADD(1 - EXTRACT(DAY FROM V_HOY) DAY TO V_HOY);

  V_FEC_VENC = DATEADD((CASE WHEN V_DIA < 1 THEN 1 ELSE V_DIA END) - 1 DAY TO V_PRIM_MES);

  IF (V_FEC_VENC < V_HOY) THEN
  BEGIN
    V_PRIM_MES = DATEADD(1 MONTH TO V_PRIM_MES);
    V_FEC_VENC = DATEADD((CASE WHEN V_DIA < 1 THEN 1 ELSE V_DIA END) - 1 DAY TO V_PRIM_MES);
  END

  RETURN DATEDIFF(DAY, V_HOY, V_FEC_VENC);
END^


-- 7) fn_vig_pres(fecha, id_presupuesto)
CREATE OR ALTER FUNCTION FN_VIG_PRES(
    P_FECHA DATE,
    P_ID_PRESUPUESTO INTEGER
)
RETURNS BOOLEAN
AS
DECLARE VARIABLE V_AI INTEGER;
DECLARE VARIABLE V_MI INTEGER;
DECLARE VARIABLE V_AF INTEGER;
DECLARE VARIABLE V_MF INTEGER;
DECLARE VARIABLE V_INI INTEGER;
DECLARE VARIABLE V_FIN INTEGER;
DECLARE VARIABLE V_FEC INTEGER;
BEGIN
  SELECT P.ANIO_INICIO, P.MES_INICIO, P.ANIO_FIN, P.MES_FIN
  FROM PRESUPUESTO P
  WHERE P.ID_PRESUPUESTO = :P_ID_PRESUPUESTO
  INTO :V_AI, :V_MI, :V_AF, :V_MF;

  IF (V_AI IS NULL OR V_MI IS NULL OR V_AF IS NULL OR V_MF IS NULL) THEN
    RETURN FALSE;

  V_INI = (V_AI * 100) + V_MI;
  V_FIN = (V_AF * 100) + V_MF;
  V_FEC = (EXTRACT(YEAR FROM P_FECHA) * 100) + EXTRACT(MONTH FROM P_FECHA);

  IF (V_FEC BETWEEN V_INI AND V_FIN) THEN RETURN TRUE;
  RETURN FALSE;
END^

-- 8) fn_cat_x_sub(id_subcategoria)
CREATE OR ALTER FUNCTION FN_CAT_X_SUB(
    P_ID_SUBCATEGORIA INTEGER
)
RETURNS INTEGER
AS
DECLARE VARIABLE V_ID_CAT INTEGER;
BEGIN
  SELECT S.ID_CATEGORIA
  FROM SUBCATEGORIA S
  WHERE S.ID_SUBCATEGORIA = :P_ID_SUBCATEGORIA
  INTO :V_ID_CAT;

  RETURN V_ID_CAT;
END^


-- 9) fn_proy_gasto(id_subcategoria, anio, mes)
CREATE OR ALTER FUNCTION FN_PROY_GASTO(
    P_ID_SUBCATEGORIA INTEGER,
    P_ANIO INTEGER,
    P_MES INTEGER
)
RETURNS DECIMAL(18,2)
AS
DECLARE VARIABLE V_HOY DATE;
DECLARE VARIABLE V_PER_HOY INTEGER;
DECLARE VARIABLE V_PER_PAR INTEGER;

DECLARE VARIABLE V_EJEC_HOY DECIMAL(18,2);
DECLARE VARIABLE V_EJEC_MES DECIMAL(18,2);

DECLARE VARIABLE V_PRIM DATE;
DECLARE VARIABLE V_SIG DATE;
DECLARE VARIABLE V_ULT DATE;

DECLARE VARIABLE V_DIAS_TOT INTEGER;
DECLARE VARIABLE V_DIAS_TRN INTEGER;

DECLARE VARIABLE V_PROY DECIMAL(18,2);
BEGIN
  V_HOY = CURRENT_DATE;
  V_PER_HOY = (EXTRACT(YEAR FROM V_HOY) * 100) + EXTRACT(MONTH FROM V_HOY);
  V_PER_PAR = (P_ANIO * 100) + P_MES;

  V_EJEC_HOY = 0;
  V_EJEC_MES = 0;
  V_PROY = 0;

  SELECT COALESCE(SUM(T.MONTO), 0)
  FROM TRANSACCION T
  INNER JOIN PRESUPUESTO_DETALLE D ON D.ID_DETALLE = T.ID_DETALLE
  WHERE D.ID_SUBCATEGORIA = :P_ID_SUBCATEGORIA
    AND T.ANIO_TRANSACCION = :P_ANIO
    AND T.MES_TRANSACCION  = :P_MES
    AND T.TIPO_TRANSACCION = 'gasto'
  INTO :V_EJEC_MES;

  IF (V_PER_PAR > V_PER_HOY) THEN RETURN 0;
  IF (V_PER_PAR < V_PER_HOY) THEN RETURN V_EJEC_MES;

  V_PRIM = DATEADD(1 - EXTRACT(DAY FROM V_HOY) DAY TO V_HOY);
  V_SIG  = DATEADD(1 MONTH TO V_PRIM);
  V_ULT  = DATEADD(-1 DAY TO V_SIG);

  V_DIAS_TOT = EXTRACT(DAY FROM V_ULT);
  V_DIAS_TRN = EXTRACT(DAY FROM V_HOY);

  SELECT COALESCE(SUM(T.MONTO), 0)
  FROM TRANSACCION T
  INNER JOIN PRESUPUESTO_DETALLE D ON D.ID_DETALLE = T.ID_DETALLE
  WHERE D.ID_SUBCATEGORIA = :P_ID_SUBCATEGORIA
    AND T.ANIO_TRANSACCION = :P_ANIO
    AND T.MES_TRANSACCION  = :P_MES
    AND T.TIPO_TRANSACCION = 'gasto'
    AND T.FECHA_TRANSACCION <= :V_HOY
  INTO :V_EJEC_HOY;

  IF (V_DIAS_TRN IS NULL OR V_DIAS_TRN <= 0 OR V_DIAS_TOT IS NULL OR V_DIAS_TOT <= 0) THEN
    V_PROY = 0;
  ELSE
    V_PROY = (V_EJEC_HOY / V_DIAS_TRN) * V_DIAS_TOT;

  RETURN V_PROY;
END^

-- 10) fn_prom_gasto(id_usuario, id_subcategoria, cantidad_meses)
CREATE OR ALTER FUNCTION FN_PROM_GASTO(
    P_ID_USUARIO INTEGER,
    P_ID_SUBCATEGORIA INTEGER,
    P_CANTIDAD_MESES INTEGER
)
RETURNS DECIMAL(18,2)
AS
DECLARE VARIABLE V_HOY DATE;
DECLARE VARIABLE V_PRIM DATE;
DECLARE VARIABLE V_INI DATE;

DECLARE VARIABLE V_FIN INTEGER;
DECLARE VARIABLE V_INICIO INTEGER;

DECLARE VARIABLE V_TOTAL DECIMAL(18,2);
BEGIN
  IF (P_CANTIDAD_MESES IS NULL OR P_CANTIDAD_MESES <= 0) THEN
    RETURN 0;

  V_HOY  = CURRENT_DATE;
  V_PRIM = DATEADD(1 - EXTRACT(DAY FROM V_HOY) DAY TO V_HOY);
  V_INI  = DATEADD(-(P_CANTIDAD_MESES - 1) MONTH TO V_PRIM);

  V_FIN    = (EXTRACT(YEAR FROM V_HOY) * 100) + EXTRACT(MONTH FROM V_HOY);
  V_INICIO = (EXTRACT(YEAR FROM V_INI) * 100) + EXTRACT(MONTH FROM V_INI);

  SELECT COALESCE(SUM(T.MONTO), 0)
  FROM TRANSACCION T
  INNER JOIN PRESUPUESTO_DETALLE D ON D.ID_DETALLE = T.ID_DETALLE
  INNER JOIN PRESUPUESTO P ON P.ID_PRESUPUESTO = D.ID_PRESUPUESTO
  WHERE P.ID_USUARIO = :P_ID_USUARIO
    AND D.ID_SUBCATEGORIA = :P_ID_SUBCATEGORIA
    AND T.TIPO_TRANSACCION = 'gasto'
    AND ((T.ANIO_TRANSACCION * 100) + T.MES_TRANSACCION) BETWEEN :V_INICIO AND :V_FIN
  INTO :V_TOTAL;

  RETURN (V_TOTAL / P_CANTIDAD_MESES);
END^

SET TERM ; ^