--SECUENCIAS PARA IDS AUTOMATICOS

CREATE SEQUENCE SEQ_USU;
CREATE SEQUENCE SEQ_CAT;
CREATE SEQUENCE SEQ_SUB;
CREATE SEQUENCE SEQ_PRE;
CREATE SEQUENCE SEQ_DET;
CREATE SEQUENCE SEQ_OBL;
CREATE SEQUENCE SEQ_TRA;

--TRIGGERS PARA ID AUTOMATICO (BEFORE INSERT)

SET TERM ^ ;

CREATE TRIGGER TR_USU_ID
FOR USUARIO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID_USUARIO IS NULL) THEN
    NEW.ID_USUARIO = GEN_ID(SEQ_USU, 1);
END^

CREATE TRIGGER TR_CAT_ID
FOR CATEGORIA
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID_CATEGORIA IS NULL) THEN
    NEW.ID_CATEGORIA = GEN_ID(SEQ_CAT, 1);
END^

CREATE TRIGGER TR_SUB_ID
FOR SUBCATEGORIA
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID_SUBCATEGORIA IS NULL) THEN
    NEW.ID_SUBCATEGORIA = GEN_ID(SEQ_SUB, 1);
END^

CREATE TRIGGER TR_PRE_ID
FOR PRESUPUESTO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID_PRESUPUESTO IS NULL) THEN
    NEW.ID_PRESUPUESTO = GEN_ID(SEQ_PRE, 1);
END^

CREATE TRIGGER TR_DET_ID
FOR PRESUPUESTO_DETALLE
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID_DETALLE IS NULL) THEN
    NEW.ID_DETALLE = GEN_ID(SEQ_DET, 1);
END^

CREATE TRIGGER TR_OBL_ID
FOR OBLIGACION_FIJA
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID_OBLIGACION IS NULL) THEN
    NEW.ID_OBLIGACION = GEN_ID(SEQ_OBL, 1);
END^

CREATE TRIGGER TR_TRA_ID
FOR TRANSACCION
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID_TRANSACCION IS NULL) THEN
    NEW.ID_TRANSACCION = GEN_ID(SEQ_TRA, 1);
END^

SET TERM ; ^

--TRIGGERS DE AUDITORIA/FECHAS (BEFORE INSERT OR UPDATE)
  
SET TERM ^ ;

CREATE TRIGGER TR_USU_AUD
FOR USUARIO
ACTIVE BEFORE INSERT OR UPDATE POSITION 0
AS
BEGIN
  IF (INSERTING) THEN
  BEGIN
    IF (NEW.CREADO_EN IS NULL) THEN
      NEW.CREADO_EN = CURRENT_TIMESTAMP;

    NEW.MODIFICADO_EN = CURRENT_TIMESTAMP;
  END

  IF (UPDATING) THEN
    NEW.MODIFICADO_EN = CURRENT_TIMESTAMP;
END^

CREATE TRIGGER TR_CAT_AUD
FOR CATEGORIA
ACTIVE BEFORE INSERT OR UPDATE POSITION 0
AS
BEGIN
  IF (INSERTING) THEN
  BEGIN
    IF (NEW.CREADO_EN IS NULL) THEN
      NEW.CREADO_EN = CURRENT_TIMESTAMP;

    NEW.MODIFICADO_EN = CURRENT_TIMESTAMP;
  END

  IF (UPDATING) THEN
    NEW.MODIFICADO_EN = CURRENT_TIMESTAMP;
END^

CREATE TRIGGER TR_SUB_AUD
FOR SUBCATEGORIA
ACTIVE BEFORE INSERT OR UPDATE POSITION 0
AS
BEGIN
  IF (INSERTING) THEN
  BEGIN
    IF (NEW.CREADO_EN IS NULL) THEN
      NEW.CREADO_EN = CURRENT_TIMESTAMP;

    NEW.MODIFICADO_EN = CURRENT_TIMESTAMP;
  END

  IF (UPDATING) THEN
    NEW.MODIFICADO_EN = CURRENT_TIMESTAMP;
END^

CREATE TRIGGER TR_PRE_AUD
FOR PRESUPUESTO
ACTIVE BEFORE INSERT OR UPDATE POSITION 0
AS
BEGIN
  IF (INSERTING) THEN
  BEGIN
    IF (NEW.CREADO_EN IS NULL) THEN
      NEW.CREADO_EN = CURRENT_TIMESTAMP;

    NEW.MODIFICADO_EN = CURRENT_TIMESTAMP;
  END

  IF (UPDATING) THEN
    NEW.MODIFICADO_EN = CURRENT_TIMESTAMP;
END^

CREATE TRIGGER TR_DET_AUD
FOR PRESUPUESTO_DETALLE
ACTIVE BEFORE INSERT OR UPDATE POSITION 0
AS
BEGIN
  IF (INSERTING) THEN
  BEGIN
    IF (NEW.CREADO_EN IS NULL) THEN
      NEW.CREADO_EN = CURRENT_TIMESTAMP;

    NEW.MODIFICADO_EN = CURRENT_TIMESTAMP;
  END

  IF (UPDATING) THEN
    NEW.MODIFICADO_EN = CURRENT_TIMESTAMP;
END^

CREATE TRIGGER TR_OBL_AUD
FOR OBLIGACION_FIJA
ACTIVE BEFORE INSERT OR UPDATE POSITION 0
AS
BEGIN
  IF (INSERTING) THEN
  BEGIN
    IF (NEW.CREADO_EN IS NULL) THEN
      NEW.CREADO_EN = CURRENT_TIMESTAMP;

    NEW.MODIFICADO_EN = CURRENT_TIMESTAMP;
  END

  IF (UPDATING) THEN
    NEW.MODIFICADO_EN = CURRENT_TIMESTAMP;
END^

CREATE TRIGGER TR_TRA_AUD
FOR TRANSACCION
ACTIVE BEFORE INSERT OR UPDATE POSITION 0
AS
BEGIN
  IF (INSERTING) THEN
  BEGIN
    IF (NEW.CREADO_EN IS NULL) THEN
      NEW.CREADO_EN = CURRENT_TIMESTAMP;

    IF (NEW.REGISTRADO_EN IS NULL) THEN
      NEW.REGISTRADO_EN = CURRENT_TIMESTAMP;

    NEW.MODIFICADO_EN = CURRENT_TIMESTAMP;
  END

  IF (UPDATING) THEN
    NEW.MODIFICADO_EN = CURRENT_TIMESTAMP;
END^

CREATE TRIGGER TR_OFT_AUD
FOR OBLIGACIONFIJA_TRANSACCION
ACTIVE BEFORE INSERT OR UPDATE POSITION 0
AS
BEGIN
  IF (INSERTING) THEN
  BEGIN
    IF (NEW.CREADO_EN IS NULL) THEN
      NEW.CREADO_EN = CURRENT_TIMESTAMP;

    NEW.MODIFICADO_EN = CURRENT_TIMESTAMP;
  END

  IF (UPDATING) THEN
    NEW.MODIFICADO_EN = CURRENT_TIMESTAMP;
END^

SET TERM ; ^

--TRIGGER OBLIGATORIO: SUBCATEGORIA "GENERAL" (AFTER INSERT)

SET TERM ^ ;

CREATE TRIGGER TR_CAT_GEN
FOR CATEGORIA
ACTIVE AFTER INSERT POSITION 0
AS
BEGIN
  INSERT INTO SUBCATEGORIA
  (
    ID_SUBCATEGORIA,
    ID_CATEGORIA,
    NOMBRE_SUBCATEGORIA,
    DESCRIPCION_SUBCATEGORIA,
    ACTIVA,
    ES_POR_DEFECTO,
    CREADO_POR,
    MODIFICADO_POR,
    CREADO_EN,
    MODIFICADO_EN
  )
  VALUES
  (
    GEN_ID(SEQ_SUB, 1),
    NEW.ID_CATEGORIA,
    'GENERAL',
    'SUBCATEGORIA CREADA AUTOMATICAMENTE',
    TRUE,
    TRUE,
    NEW.CREADO_POR,
    NEW.CREADO_POR,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  );
END^

SET TERM ; ^

--triggers adicionales
--Excepciones
CREATE EXCEPTION EX_MES_INVALIDO        'MES_TRANSACCION debe estar entre 1 y 12.';
CREATE EXCEPTION EX_VIGENCIA_INVALIDA   'La transaccion esta fuera de la vigencia del presupuesto.';
CREATE EXCEPTION EX_TIPO_INVALIDO       'TIPO_TRANSACCION no coincide con TIPO_CATEGORIA de la subcategoria.';

SET TERM ^ ;

--Sugerir Year/Month basado en FECHA_TRANSACCION (solo si viene NULL)

CREATE TRIGGER TR_TRA_SUG_PERIODO
FOR TRANSACCION
ACTIVE BEFORE INSERT POSITION 1
AS
BEGIN
  IF (NEW.FECHA_TRANSACCION IS NOT NULL) THEN
  BEGIN
    IF (NEW.ANIO_TRANSACCION IS NULL) THEN
      NEW.ANIO_TRANSACCION = EXTRACT(YEAR FROM NEW.FECHA_TRANSACCION);

    IF (NEW.MES_TRANSACCION IS NULL) THEN
      NEW.MES_TRANSACCION = EXTRACT(MONTH FROM NEW.FECHA_TRANSACCION);
  END
END^


--Validar MES 1 a 12
CREATE TRIGGER TR_TRA_VAL_MES
FOR TRANSACCION
ACTIVE BEFORE INSERT OR UPDATE POSITION 2
AS
BEGIN
  IF (NEW.MES_TRANSACCION IS NULL) THEN
    EXIT;

  IF (NEW.MES_TRANSACCION < 1 OR NEW.MES_TRANSACCION > 12) THEN
    EXCEPTION EX_MES_INVALIDO;
END^


--Validar vigencia del presupuesto (ID_DETALLE -> PRESUPUESTO)
CREATE TRIGGER TR_TRA_VAL_VIG
FOR TRANSACCION
ACTIVE BEFORE INSERT OR UPDATE POSITION 3
AS
DECLARE VARIABLE V_AI INTEGER;
DECLARE VARIABLE V_MI INTEGER;
DECLARE VARIABLE V_AF INTEGER;
DECLARE VARIABLE V_MF INTEGER;
BEGIN
  IF (NEW.ID_DETALLE IS NULL) THEN
    EXIT;

  IF (NEW.ANIO_TRANSACCION IS NULL OR NEW.MES_TRANSACCION IS NULL) THEN
    EXIT;

  V_AI = NULL; V_MI = NULL; V_AF = NULL; V_MF = NULL;

  SELECT P.ANIO_INICIO, P.MES_INICIO, P.ANIO_FIN, P.MES_FIN
  FROM PRESUPUESTO P
  INNER JOIN PRESUPUESTO_DETALLE D ON D.ID_PRESUPUESTO = P.ID_PRESUPUESTO
  WHERE D.ID_DETALLE = NEW.ID_DETALLE
  INTO :V_AI, :V_MI, :V_AF, :V_MF;

  IF (V_AI IS NULL OR V_MI IS NULL OR V_AF IS NULL OR V_MF IS NULL) THEN
    EXCEPTION EX_VIGENCIA_INVALIDA;

  IF ( ((NEW.ANIO_TRANSACCION * 12) + NEW.MES_TRANSACCION) < ((V_AI * 12) + V_MI) ) THEN
    EXCEPTION EX_VIGENCIA_INVALIDA;

  IF ( ((NEW.ANIO_TRANSACCION * 12) + NEW.MES_TRANSACCION) > ((V_AF * 12) + V_MF) ) THEN
    EXCEPTION EX_VIGENCIA_INVALIDA;
END^


--Validar TIPO_TRANSACCION y TIPO_CATEGORIA (subcategoria del detalle)
CREATE TRIGGER TR_TRA_VAL_TIPO
FOR TRANSACCION
ACTIVE BEFORE INSERT OR UPDATE POSITION 4
AS
DECLARE VARIABLE V_TIPO_CAT VARCHAR(20);
BEGIN
  IF (NEW.ID_DETALLE IS NULL) THEN
    EXIT;

  IF (NEW.TIPO_TRANSACCION IS NULL) THEN
    EXIT;

  IF (NEW.TIPO_TRANSACCION <> 'ingreso'
      AND NEW.TIPO_TRANSACCION <> 'gasto'
      AND NEW.TIPO_TRANSACCION <> 'ahorro') THEN
    EXCEPTION EX_TIPO_INVALIDO;

  V_TIPO_CAT = NULL;

  SELECT C.TIPO_CATEGORIA
  FROM CATEGORIA C
  INNER JOIN SUBCATEGORIA S ON S.ID_CATEGORIA = C.ID_CATEGORIA
  INNER JOIN PRESUPUESTO_DETALLE D ON D.ID_SUBCATEGORIA = S.ID_SUBCATEGORIA
  WHERE D.ID_DETALLE = NEW.ID_DETALLE
  INTO :V_TIPO_CAT;

  IF (V_TIPO_CAT IS NULL) THEN
    EXCEPTION EX_TIPO_INVALIDO;

  IF (NEW.TIPO_TRANSACCION <> V_TIPO_CAT) THEN
    EXCEPTION EX_TIPO_INVALIDO;
END^
SET TERM ; ^