-- 1) SECUENCIAS PARA IDS AUTOMATICOS

CREATE SEQUENCE SEQ_USU;
CREATE SEQUENCE SEQ_CAT;
CREATE SEQUENCE SEQ_SUB;
CREATE SEQUENCE SEQ_PRE;
CREATE SEQUENCE SEQ_DET;
CREATE SEQUENCE SEQ_OBL;
CREATE SEQUENCE SEQ_TRA;


  -- 2) TRIGGERS PARA ID AUTOMATICO (BEFORE INSERT)

SET TERM ^ ;

CREATE TRIGGER TR_USU_ID
FOR USUARIO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID_USUARIO IS NULL) THEN
    NEW.ID_USUARIO = GEN_ID(SEQ_USU, 1);
END^

CREATE TRIGGER TR_CAT_ID
FOR CATEGORIA
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID_CATEGORIA IS NULL) THEN
    NEW.ID_CATEGORIA = GEN_ID(SEQ_CAT, 1);
END^

CREATE TRIGGER TR_SUB_ID
FOR SUBCATEGORIA
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID_SUBCATEGORIA IS NULL) THEN
    NEW.ID_SUBCATEGORIA = GEN_ID(SEQ_SUB, 1);
END^

CREATE TRIGGER TR_PRE_ID
FOR PRESUPUESTO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID_PRESUPUESTO IS NULL) THEN
    NEW.ID_PRESUPUESTO = GEN_ID(SEQ_PRE, 1);
END^

CREATE TRIGGER TR_DET_ID
FOR PRESUPUESTO_DETALLE
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID_DETALLE IS NULL) THEN
    NEW.ID_DETALLE = GEN_ID(SEQ_DET, 1);
END^

CREATE TRIGGER TR_OBL_ID
FOR OBLIGACION_FIJA
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID_OBLIGACION IS NULL) THEN
    NEW.ID_OBLIGACION = GEN_ID(SEQ_OBL, 1);
END^

CREATE TRIGGER TR_TRA_ID
FOR TRANSACCION
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID_TRANSACCION IS NULL) THEN
    NEW.ID_TRANSACCION = GEN_ID(SEQ_TRA, 1);
END^

SET TERM ; ^


  -- 3) TRIGGERS DE AUDITORIA/FECHAS (BEFORE INSERT OR UPDATE)
  
SET TERM ^ ;

CREATE TRIGGER TR_USU_AUD
FOR USUARIO
ACTIVE BEFORE INSERT OR UPDATE POSITION 0
AS
BEGIN
  IF (INSERTING) THEN
  BEGIN
    IF (NEW.CREADO_EN IS NULL) THEN
      NEW.CREADO_EN = CURRENT_TIMESTAMP;

    NEW.MODIFICADO_EN = CURRENT_TIMESTAMP;
  END

  IF (UPDATING) THEN
    NEW.MODIFICADO_EN = CURRENT_TIMESTAMP;
END^

CREATE TRIGGER TR_CAT_AUD
FOR CATEGORIA
ACTIVE BEFORE INSERT OR UPDATE POSITION 0
AS
BEGIN
  IF (INSERTING) THEN
  BEGIN
    IF (NEW.CREADO_EN IS NULL) THEN
      NEW.CREADO_EN = CURRENT_TIMESTAMP;

    NEW.MODIFICADO_EN = CURRENT_TIMESTAMP;
  END

  IF (UPDATING) THEN
    NEW.MODIFICADO_EN = CURRENT_TIMESTAMP;
END^

CREATE TRIGGER TR_SUB_AUD
FOR SUBCATEGORIA
ACTIVE BEFORE INSERT OR UPDATE POSITION 0
AS
BEGIN
  IF (INSERTING) THEN
  BEGIN
    IF (NEW.CREADO_EN IS NULL) THEN
      NEW.CREADO_EN = CURRENT_TIMESTAMP;

    NEW.MODIFICADO_EN = CURRENT_TIMESTAMP;
  END

  IF (UPDATING) THEN
    NEW.MODIFICADO_EN = CURRENT_TIMESTAMP;
END^

CREATE TRIGGER TR_PRE_AUD
FOR PRESUPUESTO
ACTIVE BEFORE INSERT OR UPDATE POSITION 0
AS
BEGIN
  IF (INSERTING) THEN
  BEGIN
    IF (NEW.CREADO_EN IS NULL) THEN
      NEW.CREADO_EN = CURRENT_TIMESTAMP;

    NEW.MODIFICADO_EN = CURRENT_TIMESTAMP;
  END

  IF (UPDATING) THEN
    NEW.MODIFICADO_EN = CURRENT_TIMESTAMP;
END^

CREATE TRIGGER TR_DET_AUD
FOR PRESUPUESTO_DETALLE
ACTIVE BEFORE INSERT OR UPDATE POSITION 0
AS
BEGIN
  IF (INSERTING) THEN
  BEGIN
    IF (NEW.CREADO_EN IS NULL) THEN
      NEW.CREADO_EN = CURRENT_TIMESTAMP;

    NEW.MODIFICADO_EN = CURRENT_TIMESTAMP;
  END

  IF (UPDATING) THEN
    NEW.MODIFICADO_EN = CURRENT_TIMESTAMP;
END^

CREATE TRIGGER TR_OBL_AUD
FOR OBLIGACION_FIJA
ACTIVE BEFORE INSERT OR UPDATE POSITION 0
AS
BEGIN
  IF (INSERTING) THEN
  BEGIN
    IF (NEW.CREADO_EN IS NULL) THEN
      NEW.CREADO_EN = CURRENT_TIMESTAMP;

    NEW.MODIFICADO_EN = CURRENT_TIMESTAMP;
  END

  IF (UPDATING) THEN
    NEW.MODIFICADO_EN = CURRENT_TIMESTAMP;
END^

CREATE TRIGGER TR_TRA_AUD
FOR TRANSACCION
ACTIVE BEFORE INSERT OR UPDATE POSITION 0
AS
BEGIN
  IF (INSERTING) THEN
  BEGIN
    IF (NEW.CREADO_EN IS NULL) THEN
      NEW.CREADO_EN = CURRENT_TIMESTAMP;

    IF (NEW.REGISTRADO_EN IS NULL) THEN
      NEW.REGISTRADO_EN = CURRENT_TIMESTAMP;

    NEW.MODIFICADO_EN = CURRENT_TIMESTAMP;
  END

  IF (UPDATING) THEN
    NEW.MODIFICADO_EN = CURRENT_TIMESTAMP;
END^

CREATE TRIGGER TR_OFT_AUD
FOR OBLIGACIONFIJA_TRANSACCION
ACTIVE BEFORE INSERT OR UPDATE POSITION 0
AS
BEGIN
  IF (INSERTING) THEN
  BEGIN
    IF (NEW.CREADO_EN IS NULL) THEN
      NEW.CREADO_EN = CURRENT_TIMESTAMP;

    NEW.MODIFICADO_EN = CURRENT_TIMESTAMP;
  END

  IF (UPDATING) THEN
    NEW.MODIFICADO_EN = CURRENT_TIMESTAMP;
END^

SET TERM ; ^




  -- 4) TRIGGER OBLIGATORIO: SUBCATEGORIA "GENERAL" (AFTER INSERT)

SET TERM ^ ;

CREATE TRIGGER TR_CAT_GEN
FOR CATEGORIA
ACTIVE AFTER INSERT POSITION 0
AS
BEGIN
  INSERT INTO SUBCATEGORIA
  (
    ID_SUBCATEGORIA,
    ID_CATEGORIA,
    NOMBRE_SUBCATEGORIA,
    DESCRIPCION_SUBCATEGORIA,
    ACTIVA,
    ES_POR_DEFECTO,
    CREADO_POR,
    MODIFICADO_POR,
    CREADO_EN,
    MODIFICADO_EN
  )
  VALUES
  (
    GEN_ID(SEQ_SUB, 1),
    NEW.ID_CATEGORIA,
    'GENERAL',
    'SUBCATEGORIA CREADA AUTOMATICAMENTE',
    TRUE,
    TRUE,
    NEW.CREADO_POR,
    NEW.CREADO_POR,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  );
END^

SET TERM ; ^



